import { encodeCanonicalJson, SemanticArtifact } from "@bang/core";
import { M031TargetQualificationEvidenceSchema } from "@bang/evidence";
import { ExactOneCapabilityExecutionLockSchema } from "@bang/theories";
import type { FileSystem } from "effect";
import { Crypto, Effect, Encoding, Path, Schema } from "effect";
import { type PlatformError } from "effect/PlatformError";

import { publishAtomically, type PublicationEntry } from "./publication.ts";

/** The publication-level version. It increments only when the exported schema set changes shape. */
export const BANG_SCHEMA_PUBLICATION_VERSION = 2;

/** The repository-relative directory holding every schema publication. */
export const BANG_SCHEMA_PUBLICATION_DIRECTORY = "dist/schemas";

const parseOptions = { onExcessProperty: "error" } as const;

export const BangSchemaPublicationStageSchema = Schema.Literals(["generation", "publication"]);
export type BangSchemaPublicationStage = typeof BangSchemaPublicationStageSchema.Type;

export const BangSchemaPublicationReasonSchema = Schema.Literals([
  "generation-failed",
  "publication-failed",
]);
export type BangSchemaPublicationReason = typeof BangSchemaPublicationReasonSchema.Type;

/** A typed failure raised while generating or publishing the schema publication. */
export class BangSchemaPublicationFailure extends Schema.TaggedError<BangSchemaPublicationFailure>()(
  "BangSchemaPublicationFailure",
  {
    stage: BangSchemaPublicationStageSchema,
    reason: BangSchemaPublicationReasonSchema,
    path: Schema.String,
    message: Schema.String,
  },
  parseOptions,
) {}

const generationFailure = (path: string, error: unknown): BangSchemaPublicationFailure =>
  new BangSchemaPublicationFailure({
    stage: "generation",
    reason: "generation-failed",
    path,
    message: `could not generate schema publication entry ${path}: ${
      error instanceof Error ? error.message : String(error)
    }`,
  });

interface SchemaDocumentTarget {
  readonly id: string;
  readonly format: string;
  readonly file: string;
}

const documentTargets: ReadonlyArray<SchemaDocumentTarget> = [
  {
    id: "semantic-artifact",
    format: "bangSemanticArtifact:1",
    file: "schemas/bang-semantic-artifact-1.schema.json",
  },
  {
    id: "theory-lock",
    format: "bangTheoryLock:1",
    file: "schemas/bang-theory-lock-1.schema.json",
  },
  {
    id: "target-evidence",
    format: "bangTargetQualificationEvidence:1",
    file: "schemas/bang-target-evidence-1.schema.json",
  },
];

/**
 * The published consumer declaration surface. It re-exports exactly the three
 * decoded public interchange types, their strict JSON decoders, and the
 * consumption verdict type; it owns no other vocabulary.
 *
 * The verdict and record types are declared by hand instead of derived through
 * Effect's code generation: the producer Schemas carry `makeFilter` checks
 * without `toCode` callbacks, which aborts `toCodeDocument`, and a dependency-
 * free declaration keeps the published surface consumable without Effect.
 */
const CONSUMER_TYPES_SOURCE = `/**
 * Generated by \`bang export-schemas\` for BANG schema publication \\
 * ${BANG_SCHEMA_PUBLICATION_VERSION}. Do not edit; regenerate instead.
 *
 * This entry re-exports exactly the three decoded public interchange types,
 * their strict JSON decoders, and the consumption verdict type. Rejection here
 * means custody, decodability, or structural identity disagreement, never
 * semantic interpretation.
 */

/** One recorded material byte set: its role, repository-relative path, and SHA-256 digest. */
export interface BangMaterialRecord {
  readonly role: string;
  readonly path: string;
  readonly sha256: string;
}

/** Decoded shape of one \`bangTheoryLock:1\` document. */
export interface BangTheoryLock {
  readonly bangTheoryLock: 1;
  readonly selectionId: string;
  readonly package: {
    readonly path: string;
    readonly identity: { readonly id: string; readonly version: number };
    readonly semanticDigest: string;
    readonly evaluator: { readonly id: string; readonly version: number };
  };
}

/** Decoded shape of one \`bangTargetQualificationEvidence:1\` document. */
export interface BangTargetQualificationEvidence {
  readonly bangTargetQualificationEvidence: 1;
  readonly selectionId: string;
  readonly targetId: string;
  readonly realizationId: string;
  readonly artifactId: string;
  readonly artifactFormat: string;
  readonly theory: { readonly id: string; readonly version: number };
  readonly package: {
    readonly id: string;
    readonly version: number;
    readonly semanticDigest: string;
  };
  readonly requirementAddress: string;
  readonly observations: Record<string, unknown>;
  readonly materials: ReadonlyArray<BangMaterialRecord>;
  readonly producer: {
    readonly identity: string;
    readonly version: string;
    readonly targetId: string;
  };
  readonly assumptions: ReadonlyArray<string>;
  readonly weakenings: ReadonlyArray<string>;
  readonly limitations: ReadonlyArray<string>;
  readonly lifetime: string;
  readonly invalidators: ReadonlyArray<string>;
}

/** One consumption outcome: custody, decodability, and structural identity agreement only. */
export type BangConsumptionVerdict =
  | {
      readonly verdict: "valid";
      readonly verifiedMaterials: ReadonlyArray<BangMaterialRecord>;
    }
  | {
      readonly verdict: "rejected";
      readonly stage: "publication";
      readonly reason: "schema-unavailable" | "version-unsupported" | "digest-mismatch";
      readonly path?: string;
      readonly expected?: string;
      readonly observed?: string;
      readonly message: string;
    }
  | {
      readonly verdict: "rejected";
      readonly stage: "decode";
      readonly reason: "decode-failed";
      readonly path?: string;
      readonly message: string;
    }
  | {
      readonly verdict: "rejected";
      readonly stage: "custody";
      readonly reason: "material-missing" | "digest-mismatch";
      readonly path?: string;
      readonly expected?: string;
      readonly observed?: string;
      readonly message: string;
    }
  | {
      readonly verdict: "rejected";
      readonly stage: "agreement";
      readonly reason: "identity-disagreement";
      readonly identity?: string;
      readonly expected?: string;
      readonly observed?: string;
      readonly message: string;
    };

/** Strictly decode one \`bangTheoryLock:1\` document or throw a TypeError on any deviation. */
export declare function decodeBangTheoryLock(encoded: string): BangTheoryLock;

/** Strictly decode one \`bangTargetQualificationEvidence:1\` document or throw a TypeError on any deviation. */
export declare function decodeBangTargetQualificationEvidence(
  encoded: string,
): BangTargetQualificationEvidence;

/** Run the full consumption journey over supplied paths and resolve to one typed verdict. */
export declare function verifyBangConsumption(options: {
  readonly manifestPath: string;
  readonly lockPath: string;
  readonly evidencePath: string;
  readonly materialsDirectory: string;
}): Promise<BangConsumptionVerdict>;

/** The publication versions this decoder surface accepts. */
export declare const supportedBangSchemaPublicationVersions: ReadonlyArray<number>;
`;

const CONSUMER_RUNTIME_SOURCE = `/**
 * Generated by \`bang export-schemas\` for BANG schema publication \\
 * ${BANG_SCHEMA_PUBLICATION_VERSION}. Do not edit; regenerate instead.
 *
 * Strict JSON decoders for the two published record formats plus the typed
 * consumption journey. The module imports nothing but node built-ins: an
 * external consumer runs it with host built-ins alone.
 */
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";

/** Publication versions this decoder surface accepts. */
export const supportedBangSchemaPublicationVersions = [${BANG_SCHEMA_PUBLICATION_VERSION}];

const reject = (stage, reason, message, extra = {}) => ({
  verdict: "rejected",
  stage,
  reason,
  ...extra,
  message,
});

const isPlainObject = (value) =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const nonEmptyString = (value) => typeof value === "string" && value.length > 0;

const digestString = (value) =>
  typeof value === "string" && /^sha256:[0-9a-f]{64}$/.test(value);

const hexSha256 = (value) => typeof value === "string" && /^[0-9a-f]{64}$/.test(value);

const exactFields = (value, names) =>
  Object.keys(value).length === names.length && names.every((name) => name in value);

const decodeIdentity = (value) =>
  isPlainObject(value) &&
  nonEmptyString(value.id) &&
  Number.isInteger(value.version) &&
  value.version >= 1 &&
  exactFields(value, ["id", "version"]);

const decodePackageReference = (value) =>
  isPlainObject(value) &&
  nonEmptyString(value.path) &&
  decodeIdentity(value.identity) &&
  digestString(value.semanticDigest) &&
  decodeIdentity(value.evaluator) &&
  exactFields(value, ["path", "identity", "semanticDigest", "evaluator"]);

/**
 * Strict decoder for format tag \`bangTheoryLock:1\`. Excess fields are
 * errors, matching producer decoding behavior.
 */
export const decodeBangTheoryLock = (encoded) => {
  let value;
  try {
    value = JSON.parse(encoded);
  } catch {
    return undefined;
  }
  if (
    !isPlainObject(value) ||
    value.bangTheoryLock !== 1 ||
    !nonEmptyString(value.selectionId) ||
    !decodePackageReference(value.package) ||
    !exactFields(value, ["bangTheoryLock", "selectionId", "package"])
  ) {
    return undefined;
  }
  return value;
};

const qualificationText = (value) => nonEmptyString(value);

const traceKeys = [
  "valid",
  "reuse",
  "competing",
  "wrongDestination",
  "disabled",
  "defect",
  "stale",
  "replacement",
];

const observationFields = [
  "target",
  "realization",
  "entity",
  "validCall",
  "reuse",
  "competing",
  "competingSuccesses",
  "competingRejections",
  "wrongDestination",
  "disabled",
  "defect",
  "stateTrace",
  "remainingTrace",
];

const observationFieldsWithActorRestart = [...observationFields, "actorRestart"];

const actorRestartFields = [
  "oldGrantRejected",
  "freshGrantDistinct",
  "replacementGrantAccepted",
  "supervised",
];

const decodeTrace = (value) =>
  isPlainObject(value) &&
  traceKeys.every((key) => typeof value[key] === "string" && /^[0-9]+>[0-9]+$/.test(value[key])) &&
  exactFields(value, traceKeys);

const decodeObservations = (value) => {
  if (!isPlainObject(value)) return false;
  for (const key of [
    "reuse",
    "competing",
    "wrongDestination",
    "disabled",
    "defect",
    "validCall",
  ]) {
    if (typeof value[key] !== "boolean") return false;
  }
  for (const key of ["competingSuccesses", "competingRejections"]) {
    if (!Number.isInteger(value[key]) || value[key] < 0) return false;
  }
  if (
    (value.target !== "effect-typescript" && value.target !== "gleam-beam") ||
    !nonEmptyString(value.realization) ||
    !nonEmptyString(value.entity) ||
    !decodeTrace(value.stateTrace) ||
    !decodeTrace(value.remainingTrace)
  ) {
    return false;
  }
  const hasActorRestart = Object.hasOwn(value, "actorRestart");
  if (hasActorRestart) {
    const restart = value.actorRestart;
    if (
      !isPlainObject(restart) ||
      actorRestartFields.some((key) => typeof restart[key] !== "boolean") ||
      !exactFields(restart, actorRestartFields)
    ) {
      return false;
    }
  }
  return exactFields(
    value,
    hasActorRestart ? observationFieldsWithActorRestart : observationFields,
  );
};

const decodeMaterials = (value) =>
  Array.isArray(value) &&
  value.length > 0 &&
  value.every(
    (material) =>
      isPlainObject(material) &&
      nonEmptyString(material.role) &&
      nonEmptyString(material.path) &&
      hexSha256(material.sha256) &&
      exactFields(material, ["role", "path", "sha256"]),
  );

const evidenceFields = [
  "bangTargetQualificationEvidence",
  "selectionId",
  "targetId",
  "realizationId",
  "artifactId",
  "artifactFormat",
  "theory",
  "package",
  "requirementAddress",
  "observations",
  "materials",
  "producer",
  "assumptions",
  "weakenings",
  "limitations",
  "lifetime",
  "invalidators",
];

/**
 * Strict decoder for format tag \`bangTargetQualificationEvidence:1\`.
 * Excess fields are errors, matching producer decoding behavior.
 */
export const decodeBangTargetQualificationEvidence = (encoded) => {
  let value;
  try {
    value = JSON.parse(encoded);
  } catch {
    return undefined;
  }
  const textList = (value, key) => {
    if (!Array.isArray(value[key]) || value[key].length === 0) return false;
    return value[key].every((text) => qualificationText(text));
  };
  if (
    !isPlainObject(value) ||
    value.bangTargetQualificationEvidence !== 1 ||
    !nonEmptyString(value.selectionId) ||
    (value.targetId !== "effect-typescript" && value.targetId !== "gleam-beam") ||
    !nonEmptyString(value.realizationId) ||
    !nonEmptyString(value.artifactId) ||
    value.artifactFormat !== "bangSemanticArtifact:1" ||
    !decodeIdentity(value.theory) ||
    !isPlainObject(value.package) ||
    !nonEmptyString(value.package.id) ||
    !Number.isInteger(value.package.version) ||
    value.package.version < 1 ||
    !digestString(value.package.semanticDigest) ||
    !exactFields(value.package, ["id", "version", "semanticDigest"]) ||
    !nonEmptyString(value.requirementAddress) ||
    !decodeObservations(value.observations) ||
    !decodeMaterials(value.materials) ||
    !isPlainObject(value.producer) ||
    !nonEmptyString(value.producer.identity) ||
    !nonEmptyString(value.producer.version) ||
    (value.producer.targetId !== "effect-typescript" && value.producer.targetId !== "gleam-beam") ||
    !exactFields(value.producer, ["identity", "version", "targetId"]) ||
    !textList(value, "assumptions") ||
    !textList(value, "weakenings") ||
    !textList(value, "limitations") ||
    !qualificationText(value.lifetime) ||
    !textList(value, "invalidators") ||
    !exactFields(value, evidenceFields)
  ) {
    return undefined;
  }
  return value;
};

const readBytes = async (path) => {
  try {
    return new Uint8Array(await readFile(path));
  } catch {
    return undefined;
  }
};

const sha256HexOf = (bytes) => createHash("sha256").update(bytes).digest("hex");

const verifyPublishedFile = async (relativePath, expectedDigest, publicationDirectory) => {
  const bytes = await readBytes(join(publicationDirectory, relativePath));
  if (bytes === undefined) {
    return reject(
      "publication",
      "schema-unavailable",
      \`missing published file \\\${relativePath}\`,
      { path: relativePath },
    );
  }
  const observedDigest = \`sha256:\${sha256HexOf(bytes)}\`;
  if (observedDigest !== expectedDigest) {
    return reject(
      "publication",
      "digest-mismatch",
      \`published bytes differ from the manifest digest for \\\${relativePath}\`,
      { path: relativePath, expected: expectedDigest, observed: observedDigest },
    );
  }
  return undefined;
};

const verifyManifestIntegrity = async (manifestPath) => {
  const manifestBytes = await readBytes(manifestPath);
  if (manifestBytes === undefined) {
    return {
      failure: reject("publication", "schema-unavailable", \`missing manifest \\\${manifestPath}\`, {
        path: manifestPath,
      }),
    };
  }
  let manifest;
  try {
    manifest = JSON.parse(new TextDecoder().decode(manifestBytes));
  } catch {
    return {
      failure: reject("publication", "schema-unavailable", "unreadable manifest bytes", {
        path: manifestPath,
      }),
    };
  }
  if (
    !isPlainObject(manifest) ||
    manifest.bangSchemaPublication !== 1 ||
    manifest.version !== ${BANG_SCHEMA_PUBLICATION_VERSION} ||
    !Array.isArray(manifest.documents) ||
    !isPlainObject(manifest.types)
  ) {
    return {
      failure:
        !isPlainObject(manifest) || manifest.bangSchemaPublication !== 1
          ? reject("publication", "schema-unavailable", "malformed manifest structure", {
              path: manifestPath,
            })
          : reject(
              "publication",
              "version-unsupported",
              \`unsupported publication version \${String(isPlainObject(manifest) ? manifest.version : undefined)}\`,
              {
                path: manifestPath,
                expected: String(${BANG_SCHEMA_PUBLICATION_VERSION}),
                observed: String(isPlainObject(manifest) ? manifest.version : undefined),
              },
            ),
    };
  }
  for (const document of manifest.documents) {
    if (!isPlainObject(document) || typeof document.file !== "string") {
      return {
        failure: reject(
          "publication",
          "schema-unavailable",
          "malformed manifest document record",
          { path: manifestPath },
        ),
      };
    }
    const failure = await verifyPublishedFile(
      document.file,
      document.sha256,
      dirname(manifestPath),
    );
    if (failure !== undefined) return { failure };
  }
  if (typeof manifest.types.entry !== "string") {
    return {
      failure: reject(
        "publication",
        "schema-unavailable",
        "malformed manifest types record",
        { path: manifestPath },
      ),
    };
  }
  const typesFailure = await verifyPublishedFile(
    manifest.types.entry,
    manifest.types.sha256,
    dirname(manifestPath),
  );
  if (typesFailure !== undefined) return { failure: typesFailure };
  return { manifest };
};

const verifyMaterials = async (evidence, materialsDirectory) => {
  const verifiedMaterials = [];
  for (const material of evidence.materials) {
    const materialPath = join(materialsDirectory, material.path);
    const bytes = await readBytes(materialPath);
    if (bytes === undefined) {
      return reject(
        "custody",
        "material-missing",
        \`no supplied bytes for recorded material \\\${material.path}\`,
        { path: material.path },
      );
    }
    const observedDigest = sha256HexOf(bytes);
    if (observedDigest !== material.sha256) {
      return reject(
        "custody",
        "digest-mismatch",
        \`supplied bytes differ from the recorded digest for \\\${material.path}\`,
        { path: material.path, expected: material.sha256, observed: observedDigest },
      );
    }
    verifiedMaterials.push({ role: material.role, path: material.path, sha256: material.sha256 });
  }
  return { verifiedMaterials };
};

const compareRecords = (lock, evidence) => {
  if (lock.selectionId !== evidence.artifactId) {
    return reject(
      "agreement",
      "identity-disagreement",
      "theory lock selection and evidence artifact identities disagree",
      {
        identity: "artifactId",
        expected: lock.selectionId,
        observed: evidence.artifactId,
      },
    );
  }
  if (evidence.targetId !== evidence.producer.targetId) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence target and producer target identities disagree",
      {
        identity: "producer.targetId",
        expected: evidence.targetId,
        observed: evidence.producer.targetId,
      },
    );
  }
  if (evidence.targetId !== evidence.observations.target) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence target and observation target identities disagree",
      {
        identity: "observations.target",
        expected: evidence.targetId,
        observed: evidence.observations.target,
      },
    );
  }
  if (evidence.realizationId !== evidence.observations.realization) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence and observation realization identities disagree",
      {
        identity: "observations.realization",
        expected: evidence.realizationId,
        observed: evidence.observations.realization,
      },
    );
  }
  const requirementPrefix = "operationRealization:";
  const requirementMarker = ".requirement:";
  const requirementMarkerIndex = evidence.requirementAddress.indexOf(requirementMarker);
  if (
    !evidence.requirementAddress.startsWith(requirementPrefix) ||
    requirementMarkerIndex <= requirementPrefix.length ||
    requirementMarkerIndex !== evidence.requirementAddress.lastIndexOf(requirementMarker) ||
    requirementMarkerIndex + requirementMarker.length >= evidence.requirementAddress.length
  ) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence requirement address is not a structural realization requirement",
      {
        identity: "requirementAddress",
        observed: evidence.requirementAddress,
      },
    );
  }
  const requirementRealization = evidence.requirementAddress.slice(
    requirementPrefix.length,
    requirementMarkerIndex,
  );
  if (requirementRealization !== evidence.realizationId) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence requirement and realization identities disagree",
      {
        identity: "requirementAddress.realization",
        expected: evidence.realizationId,
        observed: requirementRealization,
      },
    );
  }
  if (evidence.theory.id !== evidence.package.id) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence theory and package identities disagree",
      {
        identity: "package.id",
        expected: evidence.theory.id,
        observed: evidence.package.id,
      },
    );
  }
  if (evidence.theory.version !== evidence.package.version) {
    return reject(
      "agreement",
      "identity-disagreement",
      "evidence theory and package versions disagree",
      {
        identity: "package.version",
        expected: String(evidence.theory.version),
        observed: String(evidence.package.version),
      },
    );
  }
  if (lock.package.identity.id !== evidence.theory.id) {
    return reject(
      "agreement",
      "identity-disagreement",
      "lock and evidence disagree on theory identity",
      { identity: "theory.id", expected: evidence.theory.id, observed: lock.package.identity.id },
    );
  }
  if (lock.package.identity.version !== evidence.theory.version) {
    return reject(
      "agreement",
      "identity-disagreement",
      "lock and evidence disagree on theory version",
      {
        identity: "theory.version",
        expected: String(evidence.theory.version),
        observed: String(lock.package.identity.version),
      },
    );
  }
  if (lock.package.semanticDigest !== evidence.package.semanticDigest) {
    return reject(
      "agreement",
      "identity-disagreement",
      "lock and evidence disagree on the package semantic digest",
      {
        identity: lock.package.identity.id,
        expected: evidence.package.semanticDigest,
        observed: lock.package.semanticDigest,
      },
    );
  }
  return undefined;
};

/**
 * One consumption journey over supplied artifact bytes: verify publication
 * custody against the manifest, strictly decode both records, recompute every
 * material digest, and compare structural identity agreement within the
 * evidence and against the theory lock. Emits one typed verdict and nothing
 * else.
 */
export const verifyBangConsumption = async (options) => {
  const integrity = await verifyManifestIntegrity(options.manifestPath);
  if ("failure" in integrity) return integrity.failure;
  const lockBytes = await readBytes(options.lockPath);
  if (lockBytes === undefined) {
    return reject(
      "decode",
      "decode-failed",
      \`could not read lock bytes at \\\${options.lockPath}\`,
      { path: options.lockPath },
    );
  }
  const evidenceBytes = await readBytes(options.evidencePath);
  if (evidenceBytes === undefined) {
    return reject(
      "decode",
      "decode-failed",
      \`could not read evidence bytes at \\\${options.evidencePath}\`,
      { path: options.evidencePath },
    );
  }
  const lock = decodeBangTheoryLock(new TextDecoder().decode(lockBytes));
  if (lock === undefined) {
    return reject(
      "decode",
      "decode-failed",
      \`strict decoder rejected lock document at \\\${options.lockPath}\`,
      { path: options.lockPath },
    );
  }
  const evidence = decodeBangTargetQualificationEvidence(new TextDecoder().decode(evidenceBytes));
  if (evidence === undefined) {
    return reject(
      "decode",
      "decode-failed",
      \`strict decoder rejected evidence document at \\\${options.evidencePath}\`,
      { path: options.evidencePath },
    );
  }
  const materials = await verifyMaterials(evidence, options.materialsDirectory);
  if ("message" in materials) return materials;
  const disagreement = compareRecords(lock, evidence);
  if (disagreement !== undefined) return disagreement;
  return { verdict: "valid", verifiedMaterials: materials.verifiedMaterials };
};

export default verifyBangConsumption;
`;

const encodeStableJson = (value: unknown): string => `${encodeCanonicalJson(value)}\n`;

const renderSchemaDocument = (target: SchemaDocumentTarget) =>
  Effect.try(() => {
    const sourceSchema =
      target.format === "bangSemanticArtifact:1"
        ? SemanticArtifact
        : target.format === "bangTheoryLock:1"
          ? ExactOneCapabilityExecutionLockSchema
          : M031TargetQualificationEvidenceSchema;
    const generated = Schema.toJsonSchemaDocument(sourceSchema);
    return encodeStableJson({
      $schema: "https://json-schema.org/draft/2020-12/schema",
      $id: `https://bang.local/schemas/${BANG_SCHEMA_PUBLICATION_VERSION}/${target.file}`,
      title: `BANG ${target.id} document (${target.format})`,
      ...generated.schema,
    });
  }).pipe(Effect.mapError((error) => generationFailure(target.file, error)));

/** Generate every byte of one deterministic schema publication. */
export const generateSchemaPublication = Effect.gen(function* () {
  const entries: Array<PublicationEntry> = [];
  for (const target of documentTargets) {
    entries.push({
      path: target.file,
      bytes: new TextEncoder().encode(yield* renderSchemaDocument(target)),
    });
  }
  entries.push({
    path: "types/consumer.js",
    bytes: new TextEncoder().encode(CONSUMER_RUNTIME_SOURCE),
  });
  entries.push({
    path: "types/consumer.d.ts",
    bytes: new TextEncoder().encode(CONSUMER_TYPES_SOURCE),
  });
  const digests = yield* Effect.forEach(entries, (entry) =>
    Effect.gen(function* () {
      const crypto = yield* Crypto.Crypto;
      const digest = yield* crypto.digest("SHA-256", entry.bytes);
      return [entry.path, `sha256:${Encoding.encodeHex(digest)}`] as const;
    }),
  );
  const digestByPath = Object.fromEntries(digests);
  const manifestText = encodeStableJson({
    bangSchemaPublication: 1,
    version: BANG_SCHEMA_PUBLICATION_VERSION,
    documents: documentTargets.map(({ id, format, file }) => ({
      id,
      format,
      file,
      sha256: digestByPath[file],
    })),
    types: {
      entry: "types/consumer.js",
      sha256: digestByPath["types/consumer.js"],
    },
  });
  const publishedEntries: Array<PublicationEntry> = [
    ...entries,
    { path: "manifest.json", bytes: new TextEncoder().encode(manifestText) },
  ].map((entry) => ({
    bytes: entry.bytes,
    path: `${BANG_SCHEMA_PUBLICATION_DIRECTORY}/${BANG_SCHEMA_PUBLICATION_VERSION}/${entry.path}`,
  }));
  return {
    directoryName: String(BANG_SCHEMA_PUBLICATION_VERSION),
    entries: publishedEntries,
  };
});

/**
 * Export the current publication under `dist/schemas/<version>/`, replacing an
 * existing same-version publication atomically through the house staged
 * publisher.
 */
export const runExportSchemas = (
  root: string,
): Effect.Effect<
  string,
  BangSchemaPublicationFailure | PlatformError,
  FileSystem.FileSystem | Path.Path | Crypto.Crypto
> =>
  Effect.gen(function* () {
    const path = yield* Path.Path;
    const resolvedRoot = path.resolve(root);
    const publication = yield* generateSchemaPublication;
    const destinationRelative = path.join(
      BANG_SCHEMA_PUBLICATION_DIRECTORY,
      publication.directoryName,
    );
    yield* publishAtomically(resolvedRoot, publication.entries).pipe(
      Effect.mapError((error) => {
        const failurePath =
          "path" in error && typeof error.path === "string" ? error.path : resolvedRoot;
        return new BangSchemaPublicationFailure({
          stage: "publication",
          reason: "publication-failed",
          path: failurePath,
          message: `could not publish schema publication: ${error.message}`,
        });
      }),
    );
    return destinationRelative;
  });
