import { cp, mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { describe, expect, test } from "bun:test";

const root = resolve(import.meta.dir, "..");
const publicationSource = join(root, "dist", "schemas", "1");

const lockFixture = ".bang/theory-locks/tiny-bank-packaged-exact-one.json";
const evidenceFixture =
  ".bang/qualifications/tiny-bank-two-qualified-exact-one/effect-typescript/evidence.json";
const materialFixtures = [
  "examples/tiny-bank/account.bang",
  evidenceFixture.replace(/evidence\.json$/, "boundary.ts"),
];

interface Verdict {
  readonly verdict: string;
  readonly stage?: string;
  readonly reason?: string;
  readonly path?: string;
  readonly expected?: string;
  readonly observed?: string;
  readonly message?: string;
  readonly verifiedMaterials?: ReadonlyArray<{ readonly path: string }>;
}

/**
 * The consumer script is generated by this test as a template string rather than
 * shipped inside the publication types entry: the spec fixes the types entry to
 * re-export only the three decoded types, strict decoders, and the verdict type,
 * while the journey script is test-owned driver code that wires those published
 * entries to one invocation. Importing only publication entries keeps the script
 * itself inside the sandbox contract.
 */
const consumerScript = (): string => `
// External consumer journey: imports only publication entries + node built-ins.
import { verifyBangConsumption } from "./publication/types/consumer.js";

const args = process.argv.slice(2);
const option = (name) => {
  const index = args.indexOf("--" + name);
  return index >= 0 ? args[index + 1] : undefined;
};

const verdict = await verifyBangConsumption({
  manifestPath: option("publication") + "/manifest.json",
  lockPath: option("lock"),
  evidencePath: option("evidence"),
  materialsDirectory: option("materials"),
});

process.stdout.write(JSON.stringify(verdict) + "\\n");
if (verdict.verdict !== "valid") process.exit(1);

`;

interface Sandbox {
  readonly directory: string;
  readonly manifestPath: string;
}

const buildSandbox = async (): Promise<Sandbox> => {
  const directory = await mkdtemp(join(tmpdir(), "m035-consumer-"));
  const publicationDirectory = join(directory, "publication");
  await cp(publicationSource, publicationDirectory, { recursive: true });
  await mkdir(join(directory, "inputs", "materials"), { recursive: true });
  await cp(join(root, lockFixture), join(directory, "inputs", "tiny-bank.lock.json"));
  await cp(
    join(root, evidenceFixture),
    join(directory, "inputs", "effect-typescript.evidence.json"),
  );
  await Promise.all(
    materialFixtures.map((material) =>
      cp(join(root, material), join(directory, "inputs", "materials", material)),
    ),
  );
  return {
    directory,
    manifestPath: join(publicationDirectory, "manifest.json"),
  };
};

const writeConsumer = async (directory: string): Promise<string> => {
  const scriptPath = join(directory, "consumer.mjs");
  await writeFile(scriptPath, consumerScript());
  return scriptPath;
};

const runConsumer = async (
  sandbox: Sandbox,
  overrides: Record<string, string> = {},
): Promise<{ exitCode: number; stdout: string; stderr: string }> => {
  const child = Bun.spawn(
    [
      "bun",
      "run",
      "consumer.mjs",
      "--publication",
      "publication",
      "--lock",
      "inputs/tiny-bank.lock.json",
      "--evidence",
      "inputs/effect-typescript.evidence.json",
      "--materials",
      "inputs/materials",
    ].map((argument) => overrides[argument] ?? argument),
    {
      cwd: sandbox.directory,
      stdout: "pipe",
      stderr: "pipe",
    },
  );
  const [exitCode, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  return { exitCode, stdout, stderr };
};

const parseVerdict = (stdout: string): Verdict => JSON.parse(stdout) as Verdict;

const expectRejected = async (
  label: string,
  mutate: (directory: string) => Promise<void>,
  expectedStage: string,
  expectedReason: string,
): Promise<void> => {
  const sandbox = await buildSandbox();
  try {
    await writeConsumer(sandbox.directory);
    await mutate(sandbox.directory);
    const result = await runConsumer(sandbox);
    expect(result.exitCode).not.toBe(0);
    expect(result.stdout.length).toBeGreaterThan(0);
    const verdict = parseVerdict(result.stdout);
    expect(verdict.verdict).toBe("rejected");
    expect(verdict.stage).toBe(expectedStage);
    expect(verdict.reason).toBe(expectedReason);
  } finally {
    await rm(sandbox.directory, { recursive: true, force: true });
  }
};

const rewriteManifestVersion = async (directory: string, version: number): Promise<void> => {
  const manifestPath = join(directory, "publication", "manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { version: number };
  manifest.version = version;
  await writeFile(manifestPath, `${JSON.stringify(manifest)}\n`);
};

describe("M035 external consumer journeys", () => {
  test("valid journey returns identical typed verdicts across repeated runs", async () => {
    const sandbox = await buildSandbox();
    try {
      await writeConsumer(sandbox.directory);
      const first = await runConsumer(sandbox);
      expect(first.exitCode).toBe(0);
      const firstVerdict = parseVerdict(first.stdout);
      expect(firstVerdict.verdict).toBe("valid");
      expect(firstVerdict.verifiedMaterials?.map((material) => material.path)).toEqual([
        "examples/tiny-bank/account.bang",
        materialFixtures[1]!,
      ]);
      const second = await runConsumer(sandbox);
      expect(second.exitCode).toBe(0);
      expect(second.stdout).toBe(first.stdout);
      // The consumer source names no absolute workspace path.
      const source = await readFile(join(sandbox.directory, "consumer.mjs"), "utf8");
      expect(source).not.toContain("/srv/");
      expect(source).not.toContain(root);
    } finally {
      await rm(sandbox.directory, { recursive: true, force: true });
    }
  }, 60_000);

  test("fixture 1: tampered material byte -> custody/digest-mismatch", async () => {
    await expectRejected(
      "tampered-material",
      async (directory) => {
        const materialPath = join(
          directory,
          "inputs",
          "materials",
          "examples/tiny-bank/account.bang",
        );
        const bytes = await readFile(materialPath);
        if (bytes.length > 0) bytes[0] = bytes[0]! ^ 1;
        await writeFile(materialPath, bytes);
      },
      "custody",
      "digest-mismatch",
    );
  });

  test("fixture 2: unsupported publication version -> publication/version-unsupported", async () => {
    await expectRejected(
      "unsupported-version",
      (directory) => rewriteManifestVersion(directory, 99),
      "publication",
      "version-unsupported",
    );
  });

  test("fixture 3: deleted schema file -> publication/schema-unavailable", async () => {
    await expectRejected(
      "deleted-schema",
      async (directory) => {
        await rm(join(directory, "publication", "schemas", "bang-theory-lock-1.schema.json"));
      },
      "publication",
      "schema-unavailable",
    );
  });

  test("fixture 4: malformed evidence record -> decode/decode-failed", async () => {
    await expectRejected(
      "malformed-evidence",
      async (directory) => {
        const evidencePath = join(directory, "inputs", "effect-typescript.evidence.json");
        const record = JSON.parse(await readFile(evidencePath, "utf8")) as Record<string, unknown>;
        record.extraneousField = "not in the published schema";
        await writeFile(evidencePath, JSON.stringify(record));
      },
      "decode",
      "decode-failed",
    );
  });

  test("fixture 5: tampered published schema bytes -> publication/digest-mismatch", async () => {
    await expectRejected(
      "tampered-schema",
      async (directory) => {
        const schemaPath = join(
          directory,
          "publication",
          "schemas",
          "bang-target-evidence-1.schema.json",
        );
        const original = await readFile(schemaPath, "utf8");
        await writeFile(schemaPath, `${original}\n`);
      },
      "publication",
      "digest-mismatch",
    );
  });

  test("fixture 6: missing material file -> custody/material-missing", async () => {
    await expectRejected(
      "missing-material",
      async (directory) => {
        await rm(join(directory, "inputs", "materials", "examples/tiny-bank/account.bang"));
      },
      "custody",
      "material-missing",
    );
  });

  test("fixture 7: foreign-import attempt fails and source names no workspace root", async () => {
    const sandbox = await buildSandbox();
    try {
      // A consumer script reaching toward the workspace layout via relative
      // imports fails because the sandbox copy contains only publication
      // entries and input bytes.
      await writeFile(
        join(sandbox.directory, "consumer.mjs"),
        'const module_ = await import("./packages/core/src/index.ts");\nconsole.log(JSON.stringify(module_));\n',
      );
      const child = Bun.spawn(["bun", "run", "consumer.mjs"], {
        cwd: sandbox.directory,
        stdout: "pipe",
        stderr: "pipe",
      });
      const exitCode = await child.exited;
      expect(exitCode).not.toBe(0);
      // The sandbox never contained the targeted workspace file.
      const sandboxHasWorkspace = await stat(
        join(sandbox.directory, "packages", "core", "src", "index.ts"),
      )
        .then(() => true)
        .catch(() => false);
      expect(sandboxHasWorkspace).toBe(false);
    } finally {
      await rm(sandbox.directory, { recursive: true, force: true });
    }
  }, 60_000);

  test("fixture 8: disagreeing lock and evidence selections -> agreement/identity-disagreement", async () => {
    const sandbox = await buildSandbox();
    try {
      await writeConsumer(sandbox.directory);
      // Two records from different closures: the lock keeps the real package
      // digest while the evidence record names a different one, so both
      // records still decode strictly but agreement on the package semantic
      // digest fails.
      const evidence = JSON.parse(
        await readFile(
          join(sandbox.directory, "inputs", "effect-typescript.evidence.json"),
          "utf8",
        ),
      ) as { package: { semanticDigest: string } };
      evidence.package.semanticDigest = `sha256:${"0".repeat(64)}`;
      await writeFile(
        join(sandbox.directory, "inputs", "effect-typescript.evidence.json"),
        JSON.stringify(evidence),
      );
      const result = await runConsumer(sandbox);
      expect(result.exitCode).not.toBe(0);
      const verdict = parseVerdict(result.stdout);
      expect(verdict.verdict).toBe("rejected");
      expect(verdict.stage).toBe("agreement");
      expect(verdict.reason).toBe("identity-disagreement");
    } finally {
      await rm(sandbox.directory, { recursive: true, force: true });
    }
  }, 60_000);
});
