import { describe, expect, test } from "bun:test";
import { CoreDocumentFromJson, validateCore } from "@bang/core";
import { sourceToCore } from "@bang/surface";
import {
  projectEffectData,
  projectEffectEntityOperationRealization,
  projectEffectObservableOperationRealization,
  projectEffectOperationRealization,
  projectEffectPropertySuite,
  projectEffectService,
  projectEffectSingleUseOperationRealization,
  projectEffectSingleUseOperationRealizationMaterials,
} from "@bang/target-effect";
import {
  DebitAccount,
  debitAccountGrantRemainingUses,
  makeDebitAccountLayer,
  makeWithdrawAccountOnceLayer,
  observeWithdrawAccountOnce,
  type WithdrawAccountOnceImplementation,
} from "./snapshots/M018-WithdrawAccountOnce.ts";
import { Effect, Layer, Result, Schema } from "effect";

const checkedDocument = async () => {
  const source = await Bun.file("examples/tiny-bank/account.bang").text();
  const parsed = sourceToCore(source);
  if (Result.isFailure(parsed)) throw parsed.failure;
  return Effect.runSync(validateCore(parsed.success));
};

const checkedBridgeTermDocument = async () => {
  const document = Schema.decodeSync(CoreDocumentFromJson)(
    await Bun.file("examples/bang-core/bridge-term-data.json").text(),
  );
  return Effect.runSync(validateCore(document));
};

describe("M019 runtime data projection", () => {
  test("preserves the default projection bytes when no profile is supplied", async () => {
    const document = await checkedBridgeTermDocument();
    const defaultSource = Effect.runSync(projectEffectData(document, "BridgeTerm"));
    const explicitVitestSource = Effect.runSync(
      projectEffectData(document, "BridgeTerm", { profile: "vitest" }),
    );
    const repeatedSource = Effect.runSync(projectEffectData(document, "BridgeTerm"));

    expect(defaultSource).toBe(explicitVitestSource);
    expect(defaultSource).toBe(repeatedSource);
    expect(defaultSource).toContain("// Generated by BANG M005A. Do not edit.");
    expect(defaultSource).toContain('import { expect, it } from "@effect/vitest";');
    expect(defaultSource).toContain("registerBridgeTermDecoderConformance");
  });

  test("emits a standalone runtime conformance boundary", async () => {
    const document = await checkedBridgeTermDocument();
    const source = Effect.runSync(
      projectEffectData(document, "BridgeTerm", { profile: "runtime" }),
    );

    expect(source.startsWith("// Generated by BANG M019. Do not edit.\n")).toBe(true);
    expect(source).toContain("export const BridgeTerm: Schema.Codec<BridgeTerm>");
    expect(source).toContain("const BridgeTermReference = Schema.suspend");
    expect(source).toContain("export interface BridgeTermDecoder");
    expect(source).toContain("export interface DecoderPropertyResult");
    expect(source).toContain("readonly requestedCases: number");
    expect(source).toContain("readonly maximumObservedDepth: number");
    expect(source).toContain("const BridgeTermDomainPath");
    expect(source).toContain("BridgeTermDomainPath(validCounterexample)");
    expect(source).toContain("export const checkBridgeTermDecoder");
    expect(source).not.toContain("@effect/vitest");
    expect(source).not.toContain("it.effect");
    expect(source).not.toContain("expect(");
    expect(source).not.toContain("registerBridgeTermDecoderConformance");
  });
});

describe("M008 observable operation projection", () => {
  test("derives deterministic tagged events and an invocation trace wrapper", async () => {
    const document = await checkedDocument();
    const source = Effect.runSync(
      projectEffectObservableOperationRealization(document, "WithdrawAccount"),
    );

    expect(source).toContain('export const WithdrawAccountStarted = Schema.TaggedStruct("Started"');
    expect(source).toContain(
      'export const WithdrawAccountSucceeded = Schema.TaggedStruct("Succeeded"',
    );
    expect(source).toContain(
      'export const WithdrawAccountTypedFailure = Schema.TaggedStruct("TypedFailure"',
    );
    expect(source).toContain('export const WithdrawAccountDefect = Schema.TaggedStruct("Defect"');
    expect(source).toContain("export const WithdrawAccountTraceEvent = Schema.Union([");
    expect(source).toContain(']).pipe(Schema.toTaggedUnion("_tag"));');
    expect(source).toContain("sequence: Schema.Literal(0)");
    expect(source).toContain("sequence: Schema.Literal(1)");
    expect(source).toContain('operationId: Schema.Literal("withdraw")');
    expect(source).toContain("preState: AccountState");
    expect(source).toContain("input: Schema.Struct({");
    expect(source).toContain("postState: AccountState");
    expect(source).toContain("failureId: Schema.String");
    expect(source).toContain("defect: Schema.String");
    expect(source).toContain("invocationId: string");
    expect(source).toContain("export const observeWithdrawAccountTrace = Effect.fn");
    expect(source).toContain("observeWithdrawAccount(state, amount)");
    expect(source).toContain('Match.tag("TypedFailure"');
    expect(source).toContain('Match.tag("Defect"');
    expect(source).toContain("WithdrawAccount | DebitAccount");

    const repeated = Effect.runSync(
      projectEffectObservableOperationRealization(document, "WithdrawAccount"),
    );
    expect(repeated).toBe(source);
  });

  test("leaves the existing M006 operation realization projection intact", async () => {
    const document = await checkedDocument();
    const source = Effect.runSync(projectEffectOperationRealization(document, "WithdrawAccount"));

    expect(source).toContain("// Generated by BANG M006. Do not edit.");
    expect(source).toContain("export const observeWithdrawAccount = Effect.fn");
    expect(source).toContain("WithdrawAccount | DebitAccount");
    expect(source).not.toContain("TraceEvent");
  });
});
describe("checked target entry points", () => {
  test("does not accept unchecked declarations and rejects unsupported Effect types", async () => {
    const serviceDocument = Effect.runSync(
      validateCore(
        Schema.decodeSync(CoreDocumentFromJson)(
          await Bun.file("examples/tiny-bank/core/account-service.json").text(),
        ),
      ),
    );
    const source = Effect.runSync(projectEffectService(serviceDocument, "AccountService"));
    expect(source).toContain("accountId: string");

    const unsupportedDocument = Effect.runSync(
      validateCore(
        Schema.decodeSync(CoreDocumentFromJson)(
          await Bun.file(
            "examples/core-fixtures/target-unsupported/string-represented-theory.json",
          ).text(),
        ),
      ),
    );
    const failure = Effect.runSync(
      Effect.flip(projectEffectPropertySuite(unsupportedDocument, "StringIdentity")),
    );
    expect(failure.reason).toBe("unsupported-target");
    expect(failure.message).toContain("requires Integer representation");
  });
});

describe("M015 entity operation projection", () => {
  test("keeps the complete generated Account boundary deterministic", async () => {
    const document = await checkedDocument();
    const source = Effect.runSync(
      projectEffectEntityOperationRealization(document, "Account", "WithdrawAccount"),
    );
    const repeated = Effect.runSync(
      projectEffectEntityOperationRealization(document, "Account", "WithdrawAccount"),
    );
    const snapshot = await Bun.file("tests/snapshots/M015-AccountEntity.ts").text();

    expect(source).toBe(repeated);
    expect(snapshot).toContain("export const makeAccountEntity");
    expect(source).toContain("export const AccountEntityId = Schema.String.pipe(");
    expect(source).toContain("export const AccountMessageId = Schema.String.pipe(");
    expect(source).toContain("export const AccountMessage = Schema.Union([");
    expect(source).toContain("export const AccountEntityReply = Schema.Union([");
    expect(source).toContain('parseOptions: { onExcessProperty: "error" }');
    expect(source).toContain("SynchronizedRef.modifyEffect(");
    expect(source).toContain("realization.withdraw(current, message.amount)");
    expect(source).toContain('messageType: "Withdraw" as const');
    expect(source).toContain("failureId: error._tag");

    const dispatch = source.match(
      /export interface AccountEntity \{[\s\S]*?readonly dispatch:[\s\S]*?\n\}/,
    )?.[0];
    expect(dispatch).toBeDefined();
    expect(dispatch).toContain("message: AccountMessage");
    expect(dispatch).not.toContain("state:");
    expect(dispatch).not.toContain("setState");
    const entityInterface = source.match(/export interface AccountEntity \{[\s\S]*?\n\}/)?.[0];
    expect(entityInterface).toBeDefined();

    expect(entityInterface).not.toContain("state:");

    const wrongDestination = source.indexOf("if (message.destination !== entityId)");
    const realizationCall = source.indexOf("realization.withdraw(current, message.amount)");
    expect(wrongDestination).toBeGreaterThanOrEqual(0);
    expect(realizationCall).toBeGreaterThan(wrongDestination);
  });
});
describe("M018 single-use capability projection", () => {
  test("emits a deterministic exact-one boundary and rejects unsupported quantities", async () => {
    const document = await checkedDocument();
    const unsupportedDocument = structuredClone(document);
    const source = Effect.runSync(
      projectEffectSingleUseOperationRealization(document, "WithdrawAccountOnce"),
    );
    const repeated = Effect.runSync(
      projectEffectSingleUseOperationRealization(document, "WithdrawAccountOnce"),
    );
    expect(source).toBe(repeated);
    expect(source).toContain("// Generated by BANG M018. Do not edit.");
    expect(source).toContain("export interface DebitAccountGrant");
    expect(source).toContain("export class DebitAccountGrantAlreadyConsumed");
    expect(source).toContain("export const makeDebitAccountLayer");
    expect(source).toContain("export const makeWithdrawAccountOnceLayer");
    expect(source).toContain("export const WithdrawAccountOnceObservation");
    expect(source).toContain('Schema.TaggedStruct("CapabilityUseRejected"');
    expect(source).toContain("Ref.modify");
    expect(source.indexOf("destination !== withdrawAccountOnceDestination")).toBeLessThan(
      source.indexOf("yield* consumeDebitAccountGrant"),
    );
    expect(source.indexOf("yield* consumeDebitAccountGrant")).toBeLessThan(
      source.indexOf("return yield* runImplementation"),
    );

    const realization = unsupportedDocument.declarations.find(
      (declaration) =>
        declaration.kind === "operationRealization" && declaration.id === "WithdrawAccountOnce",
    );
    if (realization === undefined || realization.kind !== "operationRealization") {
      throw new Error("WithdrawAccountOnce fixture is missing");
    }
    const requirement = realization.requires[0];
    if (requirement === undefined) throw new Error("WithdrawAccountOnce requirement is missing");
    Reflect.set(requirement, "quantity", { kind: "exactly", uses: "2" });
    const unsupported = Effect.runSync(
      Effect.flip(
        projectEffectSingleUseOperationRealization(unsupportedDocument, "WithdrawAccountOnce"),
      ),
    );
    expect(unsupported.reason).toBe("unsupported-target");
  });

  test("shares one safe symbol map across exact-one boundary and probe emission", async () => {
    const lowercaseDocument = structuredClone(await checkedDocument());
    const lowercaseRealization = lowercaseDocument.declarations.find(
      (declaration) =>
        declaration.kind === "operationRealization" && declaration.id === "WithdrawAccountOnce",
    );
    if (
      lowercaseRealization === undefined ||
      lowercaseRealization.kind !== "operationRealization"
    ) {
      throw new Error("WithdrawAccountOnce fixture is missing");
    }
    Reflect.set(lowercaseRealization, "id", "withdrawAccountOnce");
    const lowercase = Effect.runSync(
      projectEffectSingleUseOperationRealizationMaterials(lowercaseDocument, "withdrawAccountOnce"),
    );
    expect(lowercase.boundary).toContain("export class WithdrawAccountOnce");
    expect(lowercase.probe).toContain("WithdrawAccountOnce");

    const reservedDocument = structuredClone(await checkedDocument());
    const reservedMachine = reservedDocument.declarations.find(
      (declaration) => declaration.kind === "stateMachine" && declaration.id === "Account",
    );
    const reservedRealization = reservedDocument.declarations.find(
      (declaration) =>
        declaration.kind === "operationRealization" && declaration.id === "WithdrawAccountOnce",
    );
    if (
      reservedMachine === undefined ||
      reservedMachine.kind !== "stateMachine" ||
      reservedRealization === undefined ||
      reservedRealization.kind !== "operationRealization"
    ) {
      throw new Error("exact-one fixtures are missing");
    }
    Reflect.set(reservedMachine.transitions[0]!, "id", "class");
    Reflect.set(reservedRealization, "operation", {
      stateMachine: "Account",
      operation: "class",
    });
    const reserved = Effect.runSync(
      Effect.flip(
        projectEffectSingleUseOperationRealizationMaterials(
          reservedDocument,
          "WithdrawAccountOnce",
        ),
      ),
    );
    expect(reserved.reason).toBe("invalid-identifier");

    const collisionDocument = structuredClone(await checkedDocument());
    const collisionCapability = collisionDocument.declarations.find(
      (declaration) => declaration.kind === "capability" && declaration.id === "DebitAccount",
    );
    const collisionRealization = collisionDocument.declarations.find(
      (declaration) =>
        declaration.kind === "operationRealization" && declaration.id === "WithdrawAccountOnce",
    );
    if (
      collisionCapability === undefined ||
      collisionCapability.kind !== "capability" ||
      collisionRealization === undefined ||
      collisionRealization.kind !== "operationRealization"
    ) {
      throw new Error("exact-one fixtures are missing");
    }
    Reflect.set(collisionCapability, "id", "Layer");
    Reflect.set(collisionRealization.requires[0]!, "capability", "Layer");
    const collision = Effect.runSync(
      Effect.flip(
        projectEffectSingleUseOperationRealizationMaterials(
          collisionDocument,
          "WithdrawAccountOnce",
        ),
      ),
    );
    expect(collision.reason).toBe("identifier-collision");
  });

  test("consumes before execution, preserves failed grants, and serializes concurrent reuse", async () => {
    const implementation: WithdrawAccountOnceImplementation = {
      withdraw: (state, amount) => Effect.succeed({ balance: state.balance - amount }),
    };
    const boundary = Layer.mergeAll(
      makeDebitAccountLayer(),
      makeWithdrawAccountOnceLayer(implementation),
    );
    const result = await Effect.runPromise(
      Effect.gen(function* () {
        const issuer = yield* DebitAccount;
        const grant = yield* issuer.issueGrant;
        const first = yield* observeWithdrawAccountOnce(grant, "account-1", { balance: 10n }, 4n);
        const second = yield* observeWithdrawAccountOnce(grant, "account-1", first.state, 1n);
        const concurrentGrant = yield* issuer.issueGrant;
        const concurrent = yield* Effect.forEach(
          [0, 1],
          () => observeWithdrawAccountOnce(concurrentGrant, "account-1", { balance: 10n }, 4n),
          { concurrency: 2 },
        );
        return { first, second, concurrent };
      }).pipe(
        // Test registration is the conformance-harness composition root.
        // @effect-diagnostics-next-line strictEffectProvide:off
        Effect.provide(boundary),
      ),
    );
    expect(result.first).toMatchObject({
      _tag: "Success",
      state: { balance: 6n },
      remainingUses: 0,
      implementationCalls: 1,
    });
    expect(result.second).toMatchObject({
      _tag: "CapabilityUseRejected",
      failure: "DebitAccountGrantAlreadyConsumed",
      state: { balance: 6n },
      remainingUses: 0,
      implementationCalls: 1,
    });
    expect(result.concurrent.filter(({ _tag }) => _tag === "Success")).toHaveLength(1);
    expect(result.concurrent.filter(({ _tag }) => _tag === "CapabilityUseRejected")).toHaveLength(
      1,
    );
  });

  test("does not consume wrong destinations or disabled transitions", async () => {
    const implementation: WithdrawAccountOnceImplementation = {
      withdraw: (state, amount) => Effect.succeed({ balance: state.balance - amount }),
    };
    const boundary = Layer.mergeAll(
      makeDebitAccountLayer(),
      makeWithdrawAccountOnceLayer(implementation),
    );
    const result = await Effect.runPromise(
      Effect.gen(function* () {
        const issuer = yield* DebitAccount;
        const wrongGrant = yield* issuer.issueGrant;
        const wrong = yield* observeWithdrawAccountOnce(
          wrongGrant,
          "account-2",
          { balance: 10n },
          1n,
        );
        const wrongRemaining = yield* debitAccountGrantRemainingUses(wrongGrant);
        const disabledGrant = yield* issuer.issueGrant;
        const disabled = yield* observeWithdrawAccountOnce(
          disabledGrant,
          "account-1",
          { balance: 10n },
          11n,
        );
        const disabledRemaining = yield* debitAccountGrantRemainingUses(disabledGrant);
        return { wrong, wrongRemaining, disabled, disabledRemaining };
      }).pipe(
        // Test registration is the conformance-harness composition root.
        // @effect-diagnostics-next-line strictEffectProvide:off
        Effect.provide(boundary),
      ),
    );
    expect(result.wrong._tag).toBe("WrongDestination");
    expect(result.wrongRemaining).toBe(1);
    expect(result.disabled).toMatchObject({
      _tag: "DomainRejected",
      failure: "WithdrawalRejectedOnce",
      state: { balance: 10n },
      remainingUses: 1,
      implementationCalls: 0,
    });
    expect(result.disabledRemaining).toBe(1);
  });

  test("keeps a consumed grant consumed after an implementation defect", async () => {
    const implementation: WithdrawAccountOnceImplementation = {
      withdraw: () => Effect.die("controlled defect"),
    };
    const boundary = Layer.mergeAll(
      makeDebitAccountLayer(),
      makeWithdrawAccountOnceLayer(implementation),
    );
    const result = await Effect.runPromise(
      Effect.gen(function* () {
        const issuer = yield* DebitAccount;
        const grant = yield* issuer.issueGrant;
        const first = yield* observeWithdrawAccountOnce(grant, "account-1", { balance: 10n }, 4n);
        const reuse = yield* observeWithdrawAccountOnce(grant, "account-1", { balance: 10n }, 1n);
        return { first, reuse };
      }).pipe(
        // Test registration is the conformance-harness composition root.
        // @effect-diagnostics-next-line strictEffectProvide:off
        Effect.provide(boundary),
      ),
    );
    expect(result.first).toMatchObject({
      _tag: "Defect",
      failure: "implementation-defect",
      remainingUses: 0,
      implementationCalls: 1,
    });
    expect(result.reuse).toMatchObject({
      _tag: "CapabilityUseRejected",
      failure: "DebitAccountGrantAlreadyConsumed",
      remainingUses: 0,
      implementationCalls: 1,
    });
  });
});
