import { describe, expect, test } from "bun:test";
import { CoreDocumentFromJson, validateCore } from "@bang/core";
import { projectRustRefinement } from "@bang/target-rust";
import { Effect, Schema } from "effect";

const checkedBalance = async () => {
  const text = await Bun.file("examples/tiny-bank/core/balance.json").text();
  return Effect.runSync(validateCore(Schema.decodeSync(CoreDocumentFromJson)(text)));
};

const refinementDocument = (id: string, literal: string) =>
  Effect.runSync(
    validateCore({
      bangCore: 1,
      declarations: [
        {
          kind: "refinement",
          id,
          base: "Integer",
          predicate: {
            kind: "greaterThanOrEqual",
            left: { kind: "self" },
            right: { kind: "integerLiteral", value: literal },
          },
        },
      ],
    }),
  );

describe("M009 Rust portability projection", () => {
  test("projects the checked Balance boundary exactly", async () => {
    const document = await checkedBalance();
    const result = projectRustRefinement(document, "Balance");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value).toBe(
      [
        "// Generated by BANG M009. Do not edit.",
        "",
        'pub const CORE_SOURCE_ID: &str = "refinement:Balance";',
        'pub const TARGET_LIMITATION: &str = "Core Integer is limited to Rust i128";',
        "",
        "pub struct Balance(i128);",
        "",
        "pub struct BalanceError {",
        "    pub rejected: i128,",
        "}",
        "",
        "impl Balance {",
        "    pub fn new(value: i128) -> Result<Balance, BalanceError> {",
        "        if value >= 0i128 {",
        "            Ok(Balance(value))",
        "        } else {",
        "            Err(BalanceError { rejected: value })",
        "        }",
        "    }",
        "",
        "    pub fn get(self) -> i128 {",
        "        self.0",
        "    }",
        "}",
        "",
      ].join("\n"),
    );
  });

  test("rejects an Integer literal outside i128", () => {
    const result = projectRustRefinement(
      refinementDocument("Balance", "170141183460469231731687303715884105728"),
      "Balance",
    );
    expect(result).toMatchObject({ ok: false, error: { reason: "unsupported-integer-range" } });
  });

  test("rejects Rust keyword identifiers", () => {
    const result = projectRustRefinement(refinementDocument("type", "0"), "type");
    expect(result).toMatchObject({ ok: false, error: { reason: "unsupported-identifier" } });
  });
  test("rejects generated identifier collisions", () => {
    const document = Effect.runSync(
      validateCore({
        bangCore: 1,
        declarations: [
          {
            kind: "refinement",
            id: "Balance",
            base: "Integer",
            predicate: {
              kind: "greaterThanOrEqual",
              left: { kind: "self" },
              right: { kind: "integerLiteral", value: "0" },
            },
          },
          { kind: "capability", id: "BalanceError" },
        ],
      }),
    );
    expect(projectRustRefinement(document, "Balance")).toMatchObject({
      ok: false,
      error: { reason: "identifier-collision", identifier: "BalanceError" },
    });
  });

  test("rejects selectors that do not identify checked refinements", async () => {
    const document = await checkedBalance();
    expect(projectRustRefinement(document, "Missing")).toMatchObject({
      ok: false,
      error: { reason: "missing-declaration" },
    });
  });
});
