import type {
  FiniteModelDeclaration,
  RefinementDeclaration,
  ServiceDeclaration,
  StateMachineDeclaration,
  StatePredicate,
  StateValue,
  Term,
  TheoryDeclaration,
} from "@bang/core";

const projectType = (reference: string): string => {
  switch (reference) {
    case "String":
      return "string";
    case "Integer":
      return "bigint";
    default:
      return "never";
  }
};

const projectIntegerLiteral = (value: string): string => `${value}n`;
const projectStringArray = (values: ReadonlyArray<string>): string =>
  `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
const lowerFirst = (value: string): string => `${value[0]?.toLowerCase() ?? ""}${value.slice(1)}`;

const projectEffectTerm = (term: Term): string => {
  if (term.kind === "variable") return term.id;
  return `realization.${term.operation}(${term.arguments.map(projectEffectTerm).join(", ")})`;
};

export const projectEffectRefinement = (refinement: RefinementDeclaration): string => {
  if (refinement.base !== "Integer") {
    throw new TypeError(
      `Effect projection does not support ${refinement.id} over ${refinement.base}`,
    );
  }

  const minimum = projectIntegerLiteral(refinement.predicate.right.value);
  const constructor = `make${refinement.id}`;

  return `// Generated by BANG M001. Do not edit.\nimport { Order, Schema } from "effect";\n\nconst isGreaterThanOrEqualTo = Schema.makeIsGreaterThanOrEqualTo({ order: Order.BigInt });\n\nexport const ${refinement.id} = Schema.BigInt.check(isGreaterThanOrEqualTo(${minimum})).pipe(\n  Schema.brand("${refinement.id}"),\n);\nexport type ${refinement.id} = typeof ${refinement.id}.Type;\n\nexport const ${constructor} = (input: bigint): ${refinement.id} => ${refinement.id}.make(input);\n`;
};

export const projectEffectFiniteModel = (
  theory: TheoryDeclaration,
  model: FiniteModelDeclaration,
): string => {
  if (model.theory !== theory.id) {
    throw new TypeError(`model ${model.id} does not interpret theory ${theory.id}`);
  }

  const carriers = model.carriers
    .map(
      ({ sort, elements }) =>
        `export const ${sort} = Schema.Literals(${projectStringArray(elements)});\nexport type ${sort} = typeof ${sort}.Type;`,
    )
    .join("\n\n");
  const operations = theory.operations
    .map((operation) => {
      const parameters = operation.parameters.map(({ id, sort }) => `${id}: ${sort}`).join(", ");
      return `  readonly ${operation.id}: (${parameters}) => ${operation.result};`;
    })
    .join("\n");
  const cases = model.operations
    .map(({ operation, rows }) => {
      const projectedRows = rows
        .map(
          (row) =>
            `    { arguments: ${projectStringArray(row.arguments)}, result: ${JSON.stringify(row.result)} },`,
        )
        .join("\n");
      return `  ${operation}: [\n${projectedRows}\n  ],`;
    })
    .join("\n");

  return `// Generated by BANG M002. Do not edit.\nimport { Schema } from "effect";\n\n${carriers}\n\nexport interface ${theory.id}Model {\n${operations}\n}\n\nexport const ${model.id}Cases = {\n${cases}\n} as const;\n`;
};

export const projectEffectPropertySuite = (theory: TheoryDeclaration): string => {
  const sortSchemas = new Map<string, string>();
  for (const sort of theory.sorts) {
    if (sort.representation?.type !== "Integer") {
      throw new TypeError(
        `Effect property projection requires Integer representation for sort ${theory.id}.${sort.id}`,
      );
    }
    sortSchemas.set(sort.id, "Schema.BigInt");
  }
  if (theory.laws.length === 0) {
    throw new TypeError(`Effect property projection requires at least one law in ${theory.id}`);
  }

  const carriers = theory.sorts
    .map(
      ({ id }) =>
        `export const ${id} = ${sortSchemas.get(id)};\nexport type ${id} = typeof ${id}.Type;\nconst ${id}Arbitrary = Schema.toArbitrary(${id})(FastCheck);`,
    )
    .join("\n");
  const operations = theory.operations
    .map((operation) => {
      const parameters = operation.parameters.map(({ id, sort }) => `${id}: ${sort}`).join(", ");
      return `  readonly ${operation.id}: (${parameters}) => ${operation.result};`;
    })
    .join("\n");

  const predicates = theory.laws
    .map((law) => {
      if (law.parameters.length === 0) {
        throw new TypeError(
          `Effect property projection does not support nullary law ${theory.id}.${law.id}`,
        );
      }
      const parameters = law.parameters.map(({ id }) => id).join(", ");
      const left = projectEffectTerm(law.proposition.left);
      const right = projectEffectTerm(law.proposition.right);
      return `const ${law.id}Holds = (realization: ${theory.id}Model, ${law.parameters.map(({ id, sort }) => `${id}: ${sort}`).join(", ")}): boolean =>\n  ${left} === ${right};\n\nconst ${law.id}Property = (realization: ${theory.id}Model) =>\n  FastCheck.property(${law.parameters.map(({ sort }) => `${sort}Arbitrary`).join(", ")}, (${law.parameters.map(({ id, sort }) => `${id}: ${sort}`).join(", ")}) => ${law.id}Holds(realization, ${parameters}));`;
    })
    .join("\n\n");
  const registrations = theory.laws
    .map((law) => {
      const schemas = law.parameters.map(({ sort }) => sort).join(", ");
      const parameters = law.parameters.map(({ id }) => id).join(", ");
      return `  it.effect.prop(\n    "${theory.id}.${law.id}",\n    [${schemas}] as const,\n    ([${parameters}]) =>\n      Effect.sync(() => {\n        expect(${law.id}Holds(realization, ${parameters})).toBe(true);\n      }),\n    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },\n  );`;
    })
    .join("\n\n");
  const checks = theory.laws
    .map(
      (law) =>
        `  const ${law.id}Details = FastCheck.check(${law.id}Property(realization), {\n    seed: options.seed,\n    numRuns: options.numRuns,\n  });`,
    )
    .join("\n\n");
  const results = theory.laws
    .map(
      (law) => `    {
      law: "${law.id}",
      passed: !${law.id}Details.failed,
      requestedCases: options.numRuns,
      executedRuns: ${law.id}Details.numRuns,
      seed: ${law.id}Details.seed,
      numShrinks: ${law.id}Details.numShrinks,
      counterexamplePath: ${law.id}Details.counterexamplePath,
      counterexample:
        ${law.id}Details.counterexample === null
          ? null
          : ${law.id}Details.counterexample.map((value) => String(value)),
    },`,
    )
    .join("\n");

  return `// Generated by BANG M003. Do not edit.\nimport { expect, it } from "@effect/vitest";\nimport { Effect, Schema } from "effect";\nimport { FastCheck } from "effect/testing";\n\n${carriers}\n\nexport interface ${theory.id}Model {\n${operations}\n}\n\nexport interface PropertySuiteOptions {\n  readonly seed: number;\n  readonly numRuns: number;\n}\n\nexport interface PropertyLawResult {\n  readonly law: string;\n  readonly passed: boolean;\n  readonly requestedCases: number;\n  readonly executedRuns: number;\n  readonly seed: number;\n  readonly numShrinks: number;\n  readonly counterexamplePath: string | null;\n  readonly counterexample: ReadonlyArray<string> | null;\n}\n\n${predicates}\n\nexport const register${theory.id}Properties = (\n  realization: ${theory.id}Model,\n  options: PropertySuiteOptions,\n): void => {\n${registrations}\n};\n\nexport const check${theory.id}Properties = (\n  realization: ${theory.id}Model,\n  options: PropertySuiteOptions,\n): ReadonlyArray<PropertyLawResult> => {\n${checks}\n\n  return [\n${results}\n  ];\n};\n`;
};

const projectStateValue = (value: StateValue, state: string): string => {
  switch (value.kind) {
    case "parameter":
      return value.id;
    case "stateField":
      return `${state}.${value.field}`;
    case "integerLiteral":
      return projectIntegerLiteral(value.value);
  }
};

const projectStatePredicate = (predicate: StatePredicate, state: string): string =>
  `${projectStateValue(predicate.left, state)} >= ${projectStateValue(predicate.right, state)}`;

export const projectEffectStateMachine = (machine: StateMachineDeclaration): string => {
  for (const field of machine.state.fields) {
    if (field.type !== "Integer") {
      throw new TypeError(
        `Effect state-machine projection requires Integer field ${machine.id}.${field.id}`,
      );
    }
  }
  for (const operation of [...machine.initializers, ...machine.transitions]) {
    for (const parameter of operation.parameters) {
      if (parameter.type !== "Integer") {
        throw new TypeError(
          `Effect state-machine projection requires Integer parameter ${machine.id}.${operation.id}.${parameter.id}`,
        );
      }
    }
  }
  if (machine.invariants.length === 0) {
    throw new TypeError(
      `Effect state-machine projection requires at least one invariant in ${machine.id}`,
    );
  }

  const fields = machine.state.fields.map(({ id }) => `  ${id}: Schema.BigInt,`).join("\n");
  const modelInitializers = machine.initializers
    .map((operation) => {
      const parameters = operation.parameters.map(({ id }) => `${id}: bigint`).join(", ");
      return `  readonly ${operation.id}: (${parameters}) => ${machine.state.id};`;
    })
    .join("\n");
  const modelTransitions = machine.transitions
    .map((operation) => {
      const parameters = operation.parameters.map(({ id }) => `${id}: bigint`).join(", ");
      const separator = parameters.length === 0 ? "" : `, ${parameters}`;
      return `  readonly ${operation.id}: (state: ${machine.state.id}${separator}) => ${machine.state.id};`;
    })
    .join("\n");
  const invariantPredicates = machine.invariants
    .map(
      (invariant) =>
        `export const ${invariant.id}Holds = (state: ${machine.state.id}): boolean =>\n  ${projectStatePredicate(invariant.proposition, "state")};`,
    )
    .join("\n\n");
  const validState = machine.invariants.map(({ id }) => `${id}Holds(state)`).join(" && ");

  const operations = [...machine.initializers, ...machine.transitions];
  const guards = operations
    .map((operation) => {
      const isTransition = machine.transitions.some(({ id }) => id === operation.id);
      const parameters = operation.parameters.map(({ id }) => `${id}: bigint`).join(", ");
      const stateParameter = isTransition ? `state: ${machine.state.id}` : "";
      const signature = [stateParameter, parameters].filter((part) => part.length > 0).join(", ");
      const requirements = [
        ...(isTransition ? [validState] : []),
        ...operation.requires.map((requirement) => projectStatePredicate(requirement, "state")),
      ].join(" && ");
      return `export const is${operation.id[0]?.toUpperCase() ?? ""}${operation.id.slice(1)}Enabled = (${signature}): boolean =>\n  ${requirements.length === 0 ? "true" : requirements};`;
    })
    .join("\n\n");

  const inputArbitraries = operations
    .map((operation) => {
      const isTransition = machine.transitions.some(({ id }) => id === operation.id);
      const entries = [
        ...(isTransition ? ["  state: ValidStateArbitrary,"] : []),
        ...operation.parameters.map(({ id }) => `  ${id}: IntegerArbitrary,`),
      ].join("\n");
      const inputNames = [
        ...(isTransition ? ["state"] : []),
        ...operation.parameters.map(({ id }) => id),
      ].join(", ");
      const arbitraryName = `${lowerFirst(operation.id)}InputArbitrary`;
      const guardName = `is${operation.id[0]?.toUpperCase() ?? ""}${operation.id.slice(1)}Enabled`;
      return `const ${arbitraryName} = FastCheck.record({\n${entries}\n}).filter(({ ${inputNames} }) => ${guardName}(${inputNames}));`;
    })
    .join("\n\n");

  const properties = operations
    .flatMap((operation) => {
      const isTransition = machine.transitions.some(({ id }) => id === operation.id);
      const inputNames = operation.parameters.map(({ id }) => `input.${id}`).join(", ");
      const callArguments = isTransition
        ? ["input.state", inputNames].filter((part) => part.length > 0).join(", ")
        : inputNames;
      return machine.invariants.map((invariant) => {
        const propertyName = `${lowerFirst(operation.id)}${invariant.id[0]?.toUpperCase() ?? ""}${invariant.id.slice(1)}Property`;
        return `const ${propertyName} = (realization: ${machine.id}StateMachineModel) =>\n  FastCheck.property(${lowerFirst(operation.id)}InputArbitrary, (input) =>\n    ${invariant.id}Holds(realization.${operation.id}(${callArguments})),\n  );`;
      });
    })
    .join("\n\n");

  const registrations = operations
    .flatMap((operation) => {
      const isTransition = machine.transitions.some(({ id }) => id === operation.id);
      const inputNames = operation.parameters.map(({ id }) => `input.${id}`).join(", ");
      const callArguments = isTransition
        ? ["input.state", inputNames].filter((part) => part.length > 0).join(", ")
        : inputNames;
      const relation = isTransition ? "preserves" : "establishes";
      return machine.invariants.map(
        (invariant) => `  it.effect.prop(
    "${machine.id}.${operation.id} ${relation} ${invariant.id}",
    [${lowerFirst(operation.id)}InputArbitrary] as const,
    ([input]) =>
      Effect.sync(() => {
        const next = realization.${operation.id}(${callArguments});
        expect(${invariant.id}Holds(next)).toBe(true);
      }),
    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },
  );`,
      );
    })
    .join("\n\n");

  const checks = operations
    .flatMap((operation) =>
      machine.invariants.map((invariant) => {
        const details = `${lowerFirst(operation.id)}${invariant.id[0]?.toUpperCase() ?? ""}${invariant.id.slice(1)}Details`;
        const property = `${lowerFirst(operation.id)}${invariant.id[0]?.toUpperCase() ?? ""}${invariant.id.slice(1)}Property`;
        return `  const ${details} = FastCheck.check(${property}(realization), {
    seed: options.seed,
    numRuns: options.numRuns,
  });`;
      }),
    )
    .join("\n\n");

  const results = operations
    .flatMap((operation) => {
      const isTransition = machine.transitions.some(({ id }) => id === operation.id);
      const relation = isTransition ? "preserves" : "establishes";
      return machine.invariants.map((invariant) => {
        const details = `${lowerFirst(operation.id)}${invariant.id[0]?.toUpperCase() ?? ""}${invariant.id.slice(1)}Details`;
        return `    {
      obligation: "${machine.id}.${operation.id}.${relation}.${invariant.id}",
      operation: "${operation.id}",
      invariant: "${invariant.id}",
      passed: !${details}.failed,
      requestedCases: options.numRuns,
      executedRuns: ${details}.numRuns,
      numSkips: ${details}.numSkips,
      seed: ${details}.seed,
      numShrinks: ${details}.numShrinks,
      counterexamplePath: ${details}.counterexamplePath,
      counterexample:
        ${details}.counterexample === null
          ? null
          : ${details}.counterexample.map(stringifyCounterexample),
    },`;
      });
    })
    .join("\n");

  return `// Generated by BANG M004. Do not edit.\nimport { expect, it } from "@effect/vitest";\nimport { Effect, Schema } from "effect";\nimport { FastCheck } from "effect/testing";\n\nexport const ${machine.state.id} = Schema.Struct({\n${fields}\n});\nexport type ${machine.state.id} = typeof ${machine.state.id}.Type;\n\nexport interface ${machine.id}StateMachineModel {\n${modelInitializers}\n${modelTransitions}\n}\n\nexport interface StateMachineSuiteOptions {\n  readonly seed: number;\n  readonly numRuns: number;\n}\n\nexport interface StateMachineLawResult {\n  readonly obligation: string;\n  readonly operation: string;\n  readonly invariant: string;\n  readonly passed: boolean;\n  readonly requestedCases: number;\n  readonly executedRuns: number;\n  readonly numSkips: number;\n  readonly seed: number;\n  readonly numShrinks: number;\n  readonly counterexamplePath: string | null;\n  readonly counterexample: ReadonlyArray<string> | null;\n}\n\n${invariantPredicates}\n\n${guards}\n\nconst IntegerArbitrary = Schema.toArbitrary(Schema.BigInt)(FastCheck);\nconst StateArbitrary = Schema.toArbitrary(${machine.state.id})(FastCheck);\nconst ValidStateArbitrary = StateArbitrary.filter((state) => ${validState});\n\n${inputArbitraries}\n\n${properties}\n\nconst stringifyCounterexample = (value: unknown): string =>\n  JSON.stringify(value, (_key, nested) => typeof nested === "bigint" ? String(nested) : nested) ?? "undefined";\n\nexport const register${machine.id}StateMachineProperties = (\n  realization: ${machine.id}StateMachineModel,\n  options: StateMachineSuiteOptions,\n): void => {\n${registrations}\n};\n\nexport const check${machine.id}StateMachineProperties = (\n  realization: ${machine.id}StateMachineModel,\n  options: StateMachineSuiteOptions,\n): ReadonlyArray<StateMachineLawResult> => {\n${checks}\n\n  return [\n${results}\n  ];\n};\n`;
};

export const projectEffectService = (service: ServiceDeclaration): string => {
  const operations = service.operations
    .map((operation) => {
      const parameters = operation.parameters
        .map(({ id, type }) => `${id}: ${projectType(type)}`)
        .join(", ");
      return `  readonly ${operation.id}: (${parameters}) => Effect.Effect<${projectType(operation.result)}>;`;
    })
    .join("\n");

  return `// Generated by BANG M000. Do not edit.\nimport * as Context from "effect/Context";\nimport type * as Effect from "effect/Effect";\n\nexport interface ${service.id}Shape {\n${operations}\n}\n\nexport class ${service.id} extends Context.Service<${service.id}, ${service.id}Shape>()(\n  "@bang/${service.id}",\n) {}\n`;
};
