import type {
  FiniteModelDeclaration,
  RefinementDeclaration,
  ServiceDeclaration,
  TheoryDeclaration,
} from "@bang/core";

const projectType = (reference: string): string => {
  switch (reference) {
    case "String":
      return "string";
    case "Integer":
      return "bigint";
    default:
      return "never";
  }
};

const projectIntegerLiteral = (value: string): string => `${value}n`;
const projectStringArray = (values: ReadonlyArray<string>): string =>
  `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;

export const projectEffectRefinement = (refinement: RefinementDeclaration): string => {
  if (refinement.base !== "Integer") {
    throw new TypeError(
      `Effect projection does not support ${refinement.id} over ${refinement.base}`,
    );
  }

  const minimum = projectIntegerLiteral(refinement.predicate.right.value);
  const constructor = `make${refinement.id}`;

  return `// Generated by BANG M001. Do not edit.\nimport { Order, Schema } from "effect";\n\nconst isGreaterThanOrEqualTo = Schema.makeIsGreaterThanOrEqualTo({ order: Order.BigInt });\n\nexport const ${refinement.id} = Schema.BigInt.check(isGreaterThanOrEqualTo(${minimum})).pipe(\n  Schema.brand("${refinement.id}"),\n);\nexport type ${refinement.id} = typeof ${refinement.id}.Type;\n\nexport const ${constructor} = (input: bigint): ${refinement.id} => ${refinement.id}.make(input);\n`;
};

export const projectEffectFiniteModel = (
  theory: TheoryDeclaration,
  model: FiniteModelDeclaration,
): string => {
  if (model.theory !== theory.id) {
    throw new TypeError(`model ${model.id} does not interpret theory ${theory.id}`);
  }

  const carriers = model.carriers
    .map(
      ({ sort, elements }) =>
        `export const ${sort} = Schema.Literals(${projectStringArray(elements)});\nexport type ${sort} = typeof ${sort}.Type;`,
    )
    .join("\n\n");
  const operations = theory.operations
    .map((operation) => {
      const parameters = operation.parameters.map(({ id, sort }) => `${id}: ${sort}`).join(", ");
      return `  readonly ${operation.id}: (${parameters}) => ${operation.result};`;
    })
    .join("\n");
  const cases = model.operations
    .map(({ operation, rows }) => {
      const projectedRows = rows
        .map(
          (row) =>
            `    { arguments: ${projectStringArray(row.arguments)}, result: ${JSON.stringify(row.result)} },`,
        )
        .join("\n");
      return `  ${operation}: [\n${projectedRows}\n  ],`;
    })
    .join("\n");

  return `// Generated by BANG M002. Do not edit.\nimport { Schema } from "effect";\n\n${carriers}\n\nexport interface ${theory.id}Model {\n${operations}\n}\n\nexport const ${model.id}Cases = {\n${cases}\n} as const;\n`;
};

export const projectEffectService = (service: ServiceDeclaration): string => {
  const operations = service.operations
    .map((operation) => {
      const parameters = operation.parameters
        .map(({ id, type }) => `${id}: ${projectType(type)}`)
        .join(", ");
      return `  readonly ${operation.id}: (${parameters}) => Effect.Effect<${projectType(operation.result)}>;`;
    })
    .join("\n");

  return `// Generated by BANG M000. Do not edit.\nimport * as Context from "effect/Context";\nimport type * as Effect from "effect/Effect";\n\nexport interface ${service.id}Shape {\n${operations}\n}\n\nexport class ${service.id} extends Context.Service<${service.id}, ${service.id}Shape>()(\n  "@bang/${service.id}",\n) {}\n`;
};
