import type { CheckedCoreDocument, RefinementDeclaration } from "@bang/core";

export type RustTargetProjectionReason =
  | "missing-declaration"
  | "unsupported-type"
  | "unsupported-integer-range"
  | "unsupported-identifier"
  | "identifier-collision";

export interface RustTargetProjectionError {
  readonly _tag: "RustTargetProjectionError";
  readonly reason: RustTargetProjectionReason;
  readonly source: string;
  readonly message: string;
  readonly identifier?: string;
  readonly literal?: string;
}

export type RustTargetProjectionResult =
  | { readonly ok: true; readonly value: string }
  | { readonly ok: false; readonly error: RustTargetProjectionError };

const rustKeywords = new Set([
  "as",
  "async",
  "await",
  "break",
  "const",
  "continue",
  "crate",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "unsafe",
  "use",
  "where",
  "while",
  "yield",
  "try",
]);

const i128Minimum = -(1n << 127n);
const i128Maximum = (1n << 127n) - 1n;

const emitRustRefinement = (refinement: RefinementDeclaration): string => {
  const minimum = `${refinement.predicate.right.value}i128`;
  const error = `${refinement.id}Error`;

  return [
    "// Generated by BANG M009. Do not edit.",
    "",
    `pub const CORE_SOURCE_ID: &str = ${JSON.stringify(`refinement:${refinement.id}`)};`,
    'pub const TARGET_LIMITATION: &str = "Core Integer is limited to Rust i128";',
    "",
    `pub struct ${refinement.id}(i128);`,
    "",
    `pub struct ${error} {`,
    "    pub rejected: i128,",
    "}",
    "",
    `impl ${refinement.id} {`,
    `    pub fn new(value: i128) -> Result<${refinement.id}, ${error}> {`,
    `        if value >= ${minimum} {`,
    `            Ok(${refinement.id}(value))`,
    "        } else {",
    `            Err(${error} { rejected: value })`,
    "        }",
    "    }",
    "",
    "    pub fn get(self) -> i128 {",
    "        self.0",
    "    }",
    "}",
    "",
  ].join("\n");
};

const failure = (
  reason: RustTargetProjectionReason,
  source: string,
  message: string,
  details: { readonly identifier?: string; readonly literal?: string } = {},
): RustTargetProjectionResult => ({
  ok: false,
  error: { _tag: "RustTargetProjectionError", reason, source, message, ...details },
});

const validateIdentifier = (
  identifier: string,
  source: string,
): RustTargetProjectionResult | undefined => {
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(identifier)) {
    return failure(
      "unsupported-identifier",
      source,
      `Rust identifier ${identifier} is not a valid Rust identifier`,
      { identifier },
    );
  }
  if (rustKeywords.has(identifier)) {
    return failure(
      "unsupported-identifier",
      source,
      `Rust identifier ${identifier} is a reserved keyword`,
      { identifier },
    );
  }
  if (new Set(["CORE_SOURCE_ID", "TARGET_LIMITATION"]).has(identifier)) {
    return failure(
      "identifier-collision",
      source,
      `Rust identifier ${identifier} collides with a generated module constant`,
      { identifier },
    );
  }
  return undefined;
};

/** Projects a checked M009 Integer refinement into dependency-free Rust source. */
export const projectRustRefinement = (
  document: CheckedCoreDocument,
  refinementId: string,
): RustTargetProjectionResult => {
  const source = `refinement:${refinementId}`;
  const refinement = document.declarations.find(
    (declaration): declaration is RefinementDeclaration =>
      declaration.kind === "refinement" && declaration.id === refinementId,
  );
  if (refinement === undefined) {
    return failure(
      "missing-declaration",
      source,
      `Rust refinement projection cannot resolve checked refinement ${refinementId}`,
    );
  }

  const identifierFailure = validateIdentifier(refinement.id, source);
  if (identifierFailure !== undefined) return identifierFailure;
  if (refinement.base !== "Integer") {
    return failure(
      "unsupported-type",
      source,
      `Rust projection does not support ${refinement.id} over ${refinement.base}`,
    );
  }
  const literal = refinement.predicate.right.value;
  const parsed = BigInt(literal);
  if (parsed < i128Minimum || parsed > i128Maximum) {
    return failure(
      "unsupported-integer-range",
      source,
      `Rust projection cannot represent Integer literal ${literal} in i128`,
      { literal },
    );
  }
  const generatedErrorName = `${refinement.id}Error`;
  if (
    document.declarations.some(
      (declaration) =>
        declaration.id !== refinement.id &&
        (declaration.id === generatedErrorName ||
          declaration.id === "CORE_SOURCE_ID" ||
          declaration.id === "TARGET_LIMITATION"),
    )
  ) {
    return failure(
      "identifier-collision",
      source,
      `Rust projection generated identifier ${generatedErrorName} collides with a checked Core declaration`,
      { identifier: generatedErrorName },
    );
  }
  return { ok: true, value: emitRustRefinement(refinement) };
};
