import { validateCore } from "@bang/core";
import { sourceToCore } from "@bang/surface";
import { projectGleamEntityOperationRealization } from "@bang/target-gleam";
import { BunRuntime, BunServices } from "@effect/platform-bun";
import { Effect, FileSystem, Path, Schema } from "effect";
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process";

const fixture = "examples/tiny-bank/account.bang";
const packageDirectory = "generated/gleam/account-entity";
const generatedPath = `${packageDirectory}/src/bang/account_entity.gleam`;
const snapshotPath = "tests/snapshots/M017-AccountEntity.gleam";

const generatedGleamToml = `name = "account_entity"
version = "0.1.0"
target = "erlang"
gleam = ">= 1.18.1 and < 2.0.0"

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
`;

const generatedManifestToml = `# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "gleam_erlang", version = "1.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_erlang", source = "hex", outer_checksum = "1124AD3AA21143E5AF0FC5CF3D9529F6DB8CA03E43A55711B60B6B7B3874375C" },
  { name = "gleam_otp", version = "1.3.0", build_tools = ["gleam"], requirements = ["gleam_erlang", "gleam_stdlib"], otp_app = "gleam_otp", source = "hex", outer_checksum = "DE4CA6850842F0266EE95317A25DD6A0A0F20CDFAB7C0ADC2E63251D7C3C72EC" },
  { name = "gleam_stdlib", version = "1.0.5", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "CEE5B6C076A85B45F60C585F4316C63EC8B7127C119D5738C3958A9C4D50404E" },
]

[requirements]
gleam_erlang = { version = ">= 1.3.0 and < 2.0.0" }
gleam_otp = { version = ">= 1.3.0 and < 2.0.0" }
gleam_stdlib = { version = ">= 1.0.0 and < 2.0.0" }
`;

class PreparationError extends Schema.TaggedError<PreparationError>()("PreparationError", {
  message: Schema.String,
}) {}

const program = Effect.scoped(
  Effect.gen(function* () {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const document = yield* Effect.fromResult(
      sourceToCore(yield* fileSystem.readFileString(fixture)),
    );
    const checked = yield* validateCore(document);
    const projection = projectGleamEntityOperationRealization(
      checked,
      "Account",
      "WithdrawAccount",
    );
    if (!projection.ok) {
      return yield* new PreparationError({ message: projection.error.message });
    }

    yield* fileSystem.makeDirectory(path.dirname(generatedPath), { recursive: true });
    yield* fileSystem.writeFileString(`${packageDirectory}/gleam.toml`, generatedGleamToml);
    yield* fileSystem.writeFileString(`${packageDirectory}/manifest.toml`, generatedManifestToml);
    yield* fileSystem.writeFileString(generatedPath, projection.value);

    const format = yield* ChildProcess.make(
      "nix",
      ["shell", "-f", "./nix/gleam.nix", "-c", "gleam", "format", generatedPath],
      { stdout: "inherit", stderr: "inherit" },
    );
    const exitCode = yield* format.exitCode;
    if (exitCode !== ChildProcessSpawner.ExitCode(0)) {
      return yield* new PreparationError({ message: `gleam format exited ${exitCode}` });
    }

    const generated = yield* fileSystem.readFileString(generatedPath);
    if (process.env["BANG_UPDATE_SNAPSHOTS"] === "1") {
      yield* fileSystem.makeDirectory(path.dirname(snapshotPath), { recursive: true });
      yield* fileSystem.writeFileString(snapshotPath, generated);
      return;
    }

    const snapshot = yield* fileSystem.readFileString(snapshotPath);
    if (generated !== snapshot) {
      return yield* new PreparationError({
        message: `generated Gleam entity differs from ${snapshotPath}`,
      });
    }
  }),
);

// This executable module selects Bun's standard platform Layer at the composition root.
// @effect-diagnostics-next-line strictEffectProvide:off
BunRuntime.runMain(program.pipe(Effect.provide(BunServices.layer)));
