// Generated by BANG M000. Do not edit.
import * as Context from "effect/Context";
import type * as Effect from "effect/Effect";

export interface AccountServiceShape {
  readonly balance: (accountId: string) => Effect.Effect<number>;
}

export class AccountService extends Context.Service<AccountService, AccountServiceShape>()(
  "@bang/AccountService",
) {}
