// Generated by BANG M001. Do not edit.
import { Order, Schema } from "effect";

const isGreaterThanOrEqualTo = Schema.makeIsGreaterThanOrEqualTo({ order: Order.BigInt });

export const Balance = Schema.BigInt.check(isGreaterThanOrEqualTo(0n)).pipe(
  Schema.brand("Balance"),
);
export type Balance = typeof Balance.Type;

export const makeBalance = (input: bigint): Balance => Balance.make(input);
