// Generated by BANG M002. Do not edit.
import { Schema } from "effect";

export const Status = Schema.Literals(["Open", "Frozen", "Closed"]);
export type Status = typeof Status.Type;

export interface AccountLifecycleModel {
  readonly freeze: (status: Status) => Status;
}

export const AccountLifecycleValidCases = {
  freeze: [
    { arguments: ["Open"], result: "Frozen" },
    { arguments: ["Frozen"], result: "Frozen" },
    { arguments: ["Closed"], result: "Closed" },
  ],
} as const;
