// Generated by BANG M003. Do not edit.
import { expect, it } from "@effect/vitest";
import { Effect, Schema } from "effect";
import { FastCheck } from "effect/testing";

export const Value = Schema.BigInt;
export type Value = typeof Value.Type;
const ValueArbitrary = Schema.toArbitrary(Value)(FastCheck);

export interface IntegerAdditionModel {
  readonly zero: () => Value;
  readonly add: (left: Value, right: Value) => Value;
}

export interface PropertySuiteOptions {
  readonly seed: number;
  readonly numRuns: number;
}

export interface PropertyLawResult {
  readonly law: string;
  readonly passed: boolean;
  readonly requestedCases: number;
  readonly executedRuns: number;
  readonly seed: number;
  readonly numShrinks: number;
  readonly counterexamplePath: string | null;
  readonly counterexample: ReadonlyArray<string> | null;
}

const rightIdentityHolds = (realization: IntegerAdditionModel, value: Value): boolean =>
  realization.add(value, realization.zero()) === value;

const rightIdentityProperty = (realization: IntegerAdditionModel) =>
  FastCheck.property(ValueArbitrary, (value: Value) => rightIdentityHolds(realization, value));

export const registerIntegerAdditionProperties = (
  realization: IntegerAdditionModel,
  options: PropertySuiteOptions,
): void => {
  it.effect.prop(
    "IntegerAddition.rightIdentity",
    [Value] as const,
    ([value]) =>
      Effect.sync(() => {
        expect(rightIdentityHolds(realization, value)).toBe(true);
      }),
    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },
  );
};

export const checkIntegerAdditionProperties = (
  realization: IntegerAdditionModel,
  options: PropertySuiteOptions,
): ReadonlyArray<PropertyLawResult> => {
  const rightIdentityDetails = FastCheck.check(rightIdentityProperty(realization), {
    seed: options.seed,
    numRuns: options.numRuns,
  });

  return [
    {
      law: "rightIdentity",
      passed: !rightIdentityDetails.failed,
      requestedCases: options.numRuns,
      executedRuns: rightIdentityDetails.numRuns,
      seed: rightIdentityDetails.seed,
      numShrinks: rightIdentityDetails.numShrinks,
      counterexamplePath: rightIdentityDetails.counterexamplePath,
      counterexample:
        rightIdentityDetails.counterexample === null
          ? null
          : rightIdentityDetails.counterexample.map((value) => String(value)),
    },
  ];
};
