// Generated by BANG M004. Do not edit.
import { expect, it } from "@effect/vitest";
import { Effect, Schema } from "effect";
import { FastCheck } from "effect/testing";

export const AccountState = Schema.Struct({
  balance: Schema.BigInt,
});
export type AccountState = typeof AccountState.Type;

export interface AccountStateMachineModel {
  readonly initialize: (initialBalance: bigint) => AccountState;
  readonly withdraw: (state: AccountState, amount: bigint) => AccountState;
}

export interface StateMachineSuiteOptions {
  readonly seed: number;
  readonly numRuns: number;
}

export interface StateMachineLawResult {
  readonly obligation: string;
  readonly operation: string;
  readonly invariant: string;
  readonly passed: boolean;
  readonly requestedCases: number;
  readonly executedRuns: number;
  readonly numSkips: number;
  readonly seed: number;
  readonly numShrinks: number;
  readonly counterexamplePath: string | null;
  readonly counterexample: ReadonlyArray<string> | null;
}

export const nonnegativeBalanceHolds = (state: AccountState): boolean => state.balance >= 0n;

export const isInitializeEnabled = (initialBalance: bigint): boolean => initialBalance >= 0n;

export const isWithdrawEnabled = (state: AccountState, amount: bigint): boolean =>
  nonnegativeBalanceHolds(state) && amount >= 0n && state.balance >= amount;

const IntegerArbitrary = Schema.toArbitrary(Schema.BigInt)(FastCheck);
const StateArbitrary = Schema.toArbitrary(AccountState)(FastCheck);
const ValidStateArbitrary = StateArbitrary.filter((state) => nonnegativeBalanceHolds(state));

const initializeInputArbitrary = FastCheck.record({
  initialBalance: IntegerArbitrary,
}).filter(({ initialBalance }) => isInitializeEnabled(initialBalance));

const withdrawInputArbitrary = FastCheck.record({
  state: ValidStateArbitrary,
  amount: IntegerArbitrary,
}).filter(({ state, amount }) => isWithdrawEnabled(state, amount));

const initializeNonnegativeBalanceProperty = (realization: AccountStateMachineModel) =>
  FastCheck.property(initializeInputArbitrary, (input) =>
    nonnegativeBalanceHolds(realization.initialize(input.initialBalance)),
  );

const withdrawNonnegativeBalanceProperty = (realization: AccountStateMachineModel) =>
  FastCheck.property(withdrawInputArbitrary, (input) =>
    nonnegativeBalanceHolds(realization.withdraw(input.state, input.amount)),
  );

const stringifyCounterexample = (value: unknown): string =>
  JSON.stringify(value, (_key, nested) => (typeof nested === "bigint" ? String(nested) : nested)) ??
  "undefined";

export const registerAccountStateMachineProperties = (
  realization: AccountStateMachineModel,
  options: StateMachineSuiteOptions,
): void => {
  it.effect.prop(
    "Account.initialize establishes nonnegativeBalance",
    [initializeInputArbitrary] as const,
    ([input]) =>
      Effect.sync(() => {
        const next = realization.initialize(input.initialBalance);
        expect(nonnegativeBalanceHolds(next)).toBe(true);
      }),
    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },
  );

  it.effect.prop(
    "Account.withdraw preserves nonnegativeBalance",
    [withdrawInputArbitrary] as const,
    ([input]) =>
      Effect.sync(() => {
        const next = realization.withdraw(input.state, input.amount);
        expect(nonnegativeBalanceHolds(next)).toBe(true);
      }),
    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },
  );
};

export const checkAccountStateMachineProperties = (
  realization: AccountStateMachineModel,
  options: StateMachineSuiteOptions,
): ReadonlyArray<StateMachineLawResult> => {
  const initializeNonnegativeBalanceDetails = FastCheck.check(
    initializeNonnegativeBalanceProperty(realization),
    {
      seed: options.seed,
      numRuns: options.numRuns,
    },
  );

  const withdrawNonnegativeBalanceDetails = FastCheck.check(
    withdrawNonnegativeBalanceProperty(realization),
    {
      seed: options.seed,
      numRuns: options.numRuns,
    },
  );

  return [
    {
      obligation: "Account.initialize.establishes.nonnegativeBalance",
      operation: "initialize",
      invariant: "nonnegativeBalance",
      passed: !initializeNonnegativeBalanceDetails.failed,
      requestedCases: options.numRuns,
      executedRuns: initializeNonnegativeBalanceDetails.numRuns,
      numSkips: initializeNonnegativeBalanceDetails.numSkips,
      seed: initializeNonnegativeBalanceDetails.seed,
      numShrinks: initializeNonnegativeBalanceDetails.numShrinks,
      counterexamplePath: initializeNonnegativeBalanceDetails.counterexamplePath,
      counterexample:
        initializeNonnegativeBalanceDetails.counterexample === null
          ? null
          : initializeNonnegativeBalanceDetails.counterexample.map(stringifyCounterexample),
    },
    {
      obligation: "Account.withdraw.preserves.nonnegativeBalance",
      operation: "withdraw",
      invariant: "nonnegativeBalance",
      passed: !withdrawNonnegativeBalanceDetails.failed,
      requestedCases: options.numRuns,
      executedRuns: withdrawNonnegativeBalanceDetails.numRuns,
      numSkips: withdrawNonnegativeBalanceDetails.numSkips,
      seed: withdrawNonnegativeBalanceDetails.seed,
      numShrinks: withdrawNonnegativeBalanceDetails.numShrinks,
      counterexamplePath: withdrawNonnegativeBalanceDetails.counterexamplePath,
      counterexample:
        withdrawNonnegativeBalanceDetails.counterexample === null
          ? null
          : withdrawNonnegativeBalanceDetails.counterexample.map(stringifyCounterexample),
    },
  ];
};
