// Generated by BANG M005. Do not edit.
import { expect, it } from "@effect/vitest";
import { Effect, Schema } from "effect";
import { FastCheck } from "effect/testing";

export const AccountId = Schema.BigInt;
export type AccountId = typeof AccountId.Type;
const AccountIdArbitrary = Schema.toArbitrary(AccountId)(FastCheck);
export const Balance = Schema.BigInt;
export type Balance = typeof Balance.Type;

export interface AccountBalanceModel {
  readonly balance: (accountId: AccountId) => Balance;
}

export interface LedgerBalanceModel {
  readonly balance: (accountId: AccountId) => Balance;
}

export interface BridgeSuiteOptions {
  readonly seed: number;
  readonly numRuns: number;
}

export interface BridgeCounterexample {
  readonly assignment: ReadonlyArray<{ readonly parameter: string; readonly value: string }>;
  readonly leftObservation: string;
  readonly rightObservation: string;
}

export interface BridgeLawResult {
  readonly obligation: string;
  readonly bridge: string;
  readonly law: string;
  readonly participants: ReadonlyArray<string>;
  readonly passed: boolean;
  readonly requestedCases: number;
  readonly executedRuns: number;
  readonly numSkips: number;
  readonly seed: number;
  readonly numShrinks: number;
  readonly counterexamplePath: string | null;
  readonly counterexample: BridgeCounterexample | null;
}

const balancesAgreeHolds = (
  account: AccountBalanceModel,
  ledger: LedgerBalanceModel,
  accountId: AccountId,
): boolean => account.balance(accountId) === ledger.balance(accountId);

const balancesAgreeProperty = (account: AccountBalanceModel, ledger: LedgerBalanceModel) =>
  FastCheck.property(AccountIdArbitrary, (accountId: AccountId) =>
    balancesAgreeHolds(account, ledger, accountId),
  );

export const registerAccountLedgerProperties = (
  account: AccountBalanceModel,
  ledger: LedgerBalanceModel,
  options: BridgeSuiteOptions,
): void => {
  it.effect.prop(
    "AccountLedger.balancesAgree",
    [AccountId] as const,
    ([accountId]) =>
      Effect.sync(() => {
        expect(balancesAgreeHolds(account, ledger, accountId)).toBe(true);
      }),
    { fastCheck: { seed: options.seed, numRuns: options.numRuns } },
  );
};

export const checkAccountLedgerProperties = (
  account: AccountBalanceModel,
  ledger: LedgerBalanceModel,
  options: BridgeSuiteOptions,
): ReadonlyArray<BridgeLawResult> => {
  const balancesAgreeDetails = FastCheck.check(balancesAgreeProperty(account, ledger), {
    seed: options.seed,
    numRuns: options.numRuns,
  });
  const balancesAgreeCounterexample = balancesAgreeDetails.counterexample;

  return [
    {
      obligation: "AccountLedger.balancesAgree",
      bridge: "AccountLedger",
      law: "balancesAgree",
      participants: ["account:AccountBalance", "ledger:LedgerBalance"],
      passed: !balancesAgreeDetails.failed,
      requestedCases: options.numRuns,
      executedRuns: balancesAgreeDetails.numRuns,
      numSkips: balancesAgreeDetails.numSkips,
      seed: balancesAgreeDetails.seed,
      numShrinks: balancesAgreeDetails.numShrinks,
      counterexamplePath: balancesAgreeDetails.counterexamplePath,
      counterexample:
        balancesAgreeCounterexample === null
          ? null
          : {
              assignment: [
                { parameter: "accountId", value: String(balancesAgreeCounterexample[0]) },
              ],
              leftObservation: String(account.balance(balancesAgreeCounterexample[0])),
              rightObservation: String(ledger.balance(balancesAgreeCounterexample[0])),
            },
    },
  ];
};
