// Generated by BANG M005A. Do not edit.
import { expect, it } from "@effect/vitest";
import { Effect, Match, Result, Schema } from "effect";
import { FastCheck } from "effect/testing";

export const Identifier = Schema.String.pipe(
  Schema.check(Schema.isPattern(/^[A-Za-z][A-Za-z0-9]*$/)),
);
export type Identifier = typeof Identifier.Type;

/** Core source: data BridgeTerm constructor variable. */
export interface BridgeTermConstructor0 {
  readonly kind: "variable";
  readonly id: Identifier;
}

/** Core source: data BridgeTerm constructor application. */
export interface BridgeTermConstructor1 {
  readonly kind: "application";
  readonly operation: { readonly participant: Identifier; readonly operation: Identifier };
  readonly arguments: ReadonlyArray<BridgeTerm>;
}

export type BridgeTerm = BridgeTermConstructor0 | BridgeTermConstructor1;

const BridgeTermReference = Schema.suspend((): Schema.Codec<BridgeTerm> => BridgeTerm);

export const BridgeTermConstructor0: Schema.Codec<BridgeTermConstructor0> = Schema.Struct({
  kind: Schema.Literal("variable"),
  id: Identifier,
});

export const BridgeTermConstructor1: Schema.Codec<BridgeTermConstructor1> = Schema.Struct({
  kind: Schema.Literal("application"),
  operation: Schema.Struct({ participant: Identifier, operation: Identifier }),
  arguments: Schema.Array(BridgeTermReference),
});

export const BridgeTerm: Schema.Codec<BridgeTerm> = Schema.Union([
  BridgeTermConstructor0,
  BridgeTermConstructor1,
]);

export interface BridgeTermDecoder {
  readonly decode: (input: unknown) => Effect.Effect<BridgeTerm, unknown>;
}

export interface DecoderPropertyResult {
  readonly passed: boolean;
  readonly requestedCases: number;
  readonly executedRuns: number;
  readonly seed: number;
  readonly numShrinks: number;
  readonly counterexamplePath: string | null;
}

export interface BridgeTermConformanceResult {
  readonly valid: DecoderPropertyResult;
  readonly invalid: DecoderPropertyResult;
  readonly maximumObservedDepth: number;
}

const BridgeTermArbitrary = Schema.toArbitrary(BridgeTerm)(FastCheck);

const dataDepth = (value: unknown): number => {
  if (Array.isArray(value)) {
    return value.length === 0 ? 0 : 1 + Math.max(...value.map(dataDepth));
  }
  if (typeof value !== "object" || value === null) return 0;
  return 1 + Math.max(0, ...Object.values(value).map(dataDepth));
};

const BridgeTermDomainPath = (value: BridgeTerm, prefix = "BridgeTerm"): string =>
  Match.value(value).pipe(
    Match.when({ kind: "variable" }, (_candidate) => {
      const base = `${prefix}.Variable`;
      return `${base}.id`;
    }),
    Match.when({ kind: "application" }, (candidate) => {
      const base = `${prefix}.Application`;
      if (candidate["arguments"].length === 0) return `${base}.arguments`;
      const recursiveChild0 = candidate["arguments"][0];
      if (recursiveChild0 === undefined) return `${base}.arguments`;
      return BridgeTermDomainPath(recursiveChild0, `${`${base}.arguments`}[0]`);
    }),
    Match.exhaustive,
  );

const preservesValue = (left: unknown, right: unknown): boolean =>
  JSON.stringify(left) === JSON.stringify(right);

const invalidMutation = (value: BridgeTerm): unknown => ({
  ...value,
  ["kind"]: "__invalid__",
});

export const checkBridgeTermDecoder = (
  decoder: BridgeTermDecoder,
  options: { readonly seed: number; readonly numRuns: number },
): BridgeTermConformanceResult => {
  let maximumObservedDepth = 0;
  let validCounterexample: BridgeTerm | null = null;
  const validProperty = FastCheck.property(BridgeTermArbitrary, (value) => {
    maximumObservedDepth = Math.max(maximumObservedDepth, dataDepth(value));
    const decoded = Effect.runSync(Effect.result(decoder.decode(value)));
    const passed = Result.isSuccess(decoded) && preservesValue(decoded.success, value);
    if (!passed) validCounterexample = value;
    return passed;
  });
  const valid = FastCheck.check(validProperty, options);

  const invalidProperty = FastCheck.property(BridgeTermArbitrary, (value) => {
    const decoded = Effect.runSync(Effect.result(decoder.decode(invalidMutation(value))));
    return Result.isFailure(decoded);
  });
  const invalid = FastCheck.check(invalidProperty, options);

  return {
    valid: {
      passed: !valid.failed,
      requestedCases: options.numRuns,
      executedRuns: valid.numRuns,
      seed: valid.seed,
      numShrinks: valid.numShrinks,
      counterexamplePath:
        validCounterexample === null ? null : BridgeTermDomainPath(validCounterexample),
    },
    invalid: {
      passed: !invalid.failed,
      requestedCases: options.numRuns,
      executedRuns: invalid.numRuns,
      seed: invalid.seed,
      numShrinks: invalid.numShrinks,
      counterexamplePath: invalid.failed ? "BridgeTerm" : null,
    },
    maximumObservedDepth,
  };
};

export const registerBridgeTermDecoderConformance = (
  decoder: BridgeTermDecoder,
  options: { readonly seed: number; readonly numRuns: number },
): void => {
  it.effect("BridgeTerm decoder accepts and preserves generated valid values", () =>
    Effect.sync(() => {
      const result = checkBridgeTermDecoder(decoder, options);
      expect(result.valid.passed).toBe(true);
    }),
  );
  it.effect("BridgeTerm decoder rejects generated invalid mutations", () =>
    Effect.sync(() => {
      const result = checkBridgeTermDecoder(decoder, options);
      expect(result.invalid.passed).toBe(true);
    }),
  );
};
