// Generated by BANG M006. Do not edit.
import { expect, it } from "@effect/vitest";
import { Cause, Context, Effect, Layer, Match, Option, Schema } from "effect";

export const AccountState = Schema.Struct({
  balance: Schema.BigInt,
});
export type AccountState = typeof AccountState.Type;

export const isWithdrawEnabled = (state: AccountState, amount: bigint): boolean =>
  state.balance >= 0n && amount >= 0n && state.balance >= amount;

export class WithdrawalRejected extends Schema.TaggedError<WithdrawalRejected>()(
  "WithdrawalRejected",
  {
    state: AccountState,
    amount: Schema.BigInt,
  },
) {}

export interface DebitAccountShape {
  readonly declaration: "DebitAccount";
}

export class DebitAccount extends Context.Service<DebitAccount, DebitAccountShape>()(
  "@bang/capability/DebitAccount",
) {}

export interface WithdrawAccountShape {
  readonly withdraw: (
    state: AccountState,
    amount: bigint,
  ) => Effect.Effect<AccountState, WithdrawalRejected, DebitAccount>;
}

export type WithdrawAccountRequirements = Effect.Services<
  ReturnType<WithdrawAccountShape["withdraw"]>
>;

export class WithdrawAccount extends Context.Service<WithdrawAccount, WithdrawAccountShape>()(
  "@bang/realization/WithdrawAccount",
) {}

export interface WithdrawAccountImplementation {
  readonly withdraw: (state: AccountState, amount: bigint) => Effect.Effect<AccountState>;
}

export const makeWithdrawAccountLayer = (
  implementation: WithdrawAccountImplementation,
): Layer.Layer<WithdrawAccount> =>
  Layer.succeed(
    WithdrawAccount,
    WithdrawAccount.of({
      withdraw: Effect.fn("WithdrawAccount.withdraw")(function* (
        state: AccountState,
        amount: bigint,
      ) {
        yield* DebitAccount;
        if (!isWithdrawEnabled(state, amount)) {
          return yield* new WithdrawalRejected({ state, amount });
        }
        return yield* implementation.withdraw(state, amount);
      }),
    }),
  );

export type WithdrawAccountObservation =
  | { readonly _tag: "Success"; readonly state: AccountState }
  | { readonly _tag: "TypedFailure"; readonly error: WithdrawalRejected }
  | { readonly _tag: "Defect"; readonly defect: string }
  | { readonly _tag: "UnexpectedFailure"; readonly cause: string };

export const observeWithdrawAccount = Effect.fn("observeWithdrawAccount")(function* (
  state: AccountState,
  amount: bigint,
): Effect.fn.Return<WithdrawAccountObservation, never, WithdrawAccount | DebitAccount> {
  const service = yield* WithdrawAccount;
  const exit = yield* Effect.exit(service.withdraw(state, amount));
  return Match.value(exit).pipe(
    Match.tag("Success", ({ value }) => ({ _tag: "Success" as const, state: value })),
    Match.tag("Failure", ({ cause }): WithdrawAccountObservation => {
      if (Cause.hasDies(cause)) {
        return { _tag: "Defect", defect: Cause.pretty(cause) };
      }
      const error = Cause.findErrorOption(cause);
      if (Option.isSome(error)) {
        return { _tag: "TypedFailure", error: error.value };
      }
      return { _tag: "UnexpectedFailure", cause: Cause.pretty(cause) };
    }),
    Match.exhaustive,
  );
});

export const registerWithdrawAccountConformance = (
  lawful: Layer.Layer<WithdrawAccount>,
  defecting: Layer.Layer<WithdrawAccount>,
  capability: Layer.Layer<DebitAccount>,
  scenarios: {
    readonly enabled: {
      readonly state: AccountState;
      readonly amount: bigint;
      readonly expectedState: AccountState;
    };
    readonly disabled: {
      readonly state: AccountState;
      readonly amount: bigint;
    };
  },
): void => {
  const lawfulBoundary = Layer.mergeAll(lawful, capability);
  const defectingBoundary = Layer.mergeAll(defecting, capability);

  it.effect("WithdrawAccount succeeds for an enabled Account.withdraw", () =>
    observeWithdrawAccount(scenarios.enabled.state, scenarios.enabled.amount).pipe(
      // Test registration is the conformance-harness composition root.
      // @effect-diagnostics-next-line strictEffectProvide:off
      Effect.provide(lawfulBoundary),
      Effect.map((observation) =>
        Match.value(observation).pipe(
          Match.tag("Success", ({ state }) => {
            expect(state).toEqual(scenarios.enabled.expectedState);
            expect(state.balance >= 0n).toBe(true);
          }),
          Match.orElse(() => expect.fail("expected success")),
        ),
      ),
    ),
  );

  it.effect("WithdrawAccount returns WithdrawalRejected for a disabled request", () =>
    observeWithdrawAccount(scenarios.disabled.state, scenarios.disabled.amount).pipe(
      // Test registration is the conformance-harness composition root.
      // @effect-diagnostics-next-line strictEffectProvide:off
      Effect.provide(lawfulBoundary),
      Effect.map((observation) =>
        Match.value(observation).pipe(
          Match.tag("TypedFailure", ({ error }) => {
            expect(error.state).toEqual(scenarios.disabled.state);
            expect(error.amount).toBe(scenarios.disabled.amount);
          }),
          Match.orElse(() => expect.fail("expected typed failure")),
        ),
      ),
    ),
  );

  it.effect("WithdrawAccount reports an implementation defect separately", () =>
    observeWithdrawAccount(scenarios.enabled.state, scenarios.enabled.amount).pipe(
      // Test registration is the conformance-harness composition root.
      // @effect-diagnostics-next-line strictEffectProvide:off
      Effect.provide(defectingBoundary),
      Effect.map((observation) =>
        Match.value(observation).pipe(
          Match.tag("Defect", ({ defect }) => expect(defect.length).toBeGreaterThan(0)),
          Match.orElse(() => expect.fail("expected defect")),
        ),
      ),
    ),
  );
};
