// Generated by BANG M009. Do not edit.

pub const CORE_SOURCE_ID: &str = "refinement:Balance";
pub const TARGET_LIMITATION: &str = "Core Integer is limited to Rust i128";

pub struct Balance(i128);

pub struct BalanceError {
    pub rejected: i128,
}

impl Balance {
    pub fn new(value: i128) -> Result<Balance, BalanceError> {
        if value >= 0i128 {
            Ok(Balance(value))
        } else {
            Err(BalanceError { rejected: value })
        }
    }

    pub fn get(self) -> i128 {
        self.0
    }
}
