//// Generated by BANG M017. Do not edit.
//// Checked Core: Account.initialize, Account.withdraw, WithdrawAccount, DebitAccount, WithdrawalRejected.
//// This module is a deterministic target projection, not a Core authority.

import gleam/dynamic
import gleam/dynamic/decode
import gleam/erlang/process
import gleam/otp/actor
import gleam/otp/static_supervisor
import gleam/otp/supervision

pub const core_state_machine_id = "Account"

pub const core_initializer_id = "initialize"

pub const core_operation_id = "withdraw"

pub const core_realization_id = "WithdrawAccount"

pub const core_capability_id = "DebitAccount"

pub const core_failure_id = "WithdrawalRejected"

pub const message_type = "Withdraw"

pub const account_entity_id = "account-1"

pub type AccountState {
  AccountState(balance: Int)
}

pub opaque type DebitAccount {
  DebitAccount
}

pub fn debit_account() -> DebitAccount {
  DebitAccount
}

pub type Reply {
  Succeeded(
    entity_id: String,
    message_id: String,
    message_type: String,
    state: AccountState,
  )
  TypedFailure(
    entity_id: String,
    message_id: String,
    message_type: String,
    failure_id: String,
    state: AccountState,
  )
  WrongDestination(
    entity_id: String,
    message_id: String,
    message_type: String,
    destination: String,
    state: AccountState,
  )
}

pub type ExternalMessageRejected {
  ExternalMessageRejected
}

pub type StartError {
  InvalidInitialBalance(balance: Int)
  SupervisorStartFailed
}

pub opaque type Account {
  Account(
    name: process.Name(Message),
    supervisor_pid: process.Pid,
    entity_id: String,
  )
}

pub type Message {
  Withdraw(
    reply_to: process.Subject(Reply),
    destination: String,
    message_id: String,
    amount: Int,
  )
  Balance(reply_to: process.Subject(Int))
  Stop(reply_to: process.Subject(Nil))
  ForceFailure
}

fn handle_message(
  entity_id: String,
  state: AccountState,
  message: Message,
) -> actor.Next(AccountState, Message) {
  case message {
    Withdraw(reply_to:, destination:, message_id:, amount:) -> {
      let accepted =
        destination == entity_id && amount >= 0 && state.balance >= amount
      let next_state = case accepted {
        True -> AccountState(balance: state.balance - amount)
        False -> state
      }
      let reply = case destination == entity_id {
        False ->
          WrongDestination(
            entity_id: entity_id,
            message_id: message_id,
            message_type: message_type,
            destination: destination,
            state: state,
          )
        True ->
          case accepted {
            True ->
              Succeeded(
                entity_id: entity_id,
                message_id: message_id,
                message_type: message_type,
                state: next_state,
              )
            False ->
              TypedFailure(
                entity_id: entity_id,
                message_id: message_id,
                message_type: message_type,
                failure_id: core_failure_id,
                state: state,
              )
          }
      }
      actor.send(reply_to, reply)
      actor.continue(next_state)
    }
    Balance(reply_to) -> {
      actor.send(reply_to, state.balance)
      actor.continue(state)
    }
    Stop(reply_to) -> {
      actor.send(reply_to, Nil)
      actor.stop()
    }
    ForceFailure -> actor.stop_abnormal("controlled failure")
  }
}

fn start_actor(
  name: process.Name(Message),
  initial_balance: Int,
) -> actor.StartResult(process.Subject(Message)) {
  actor.new(AccountState(balance: initial_balance))
  |> actor.named(name)
  |> actor.on_message(fn(state, message) {
    handle_message(account_entity_id, state, message)
  })
  |> actor.start
}

pub fn start_supervised(
  name: process.Name(Message),
  initial_balance: Int,
) -> Result(Account, StartError) {
  case initial_balance < 0 {
    True -> Error(InvalidInitialBalance(initial_balance))
    False -> {
      let child =
        supervision.worker(fn() { start_actor(name, initial_balance) })
        |> supervision.restart(supervision.Transient)
        |> supervision.significant(True)
      let builder =
        static_supervisor.new(static_supervisor.OneForOne)
        |> static_supervisor.auto_shutdown(static_supervisor.AnySignificant)
        |> static_supervisor.add(child)
      case static_supervisor.start(builder) {
        Ok(started) -> {
          process.unlink(started.pid)
          Ok(Account(
            name: name,
            supervisor_pid: started.pid,
            entity_id: account_entity_id,
          ))
        }
        Error(_) -> Error(SupervisorStartFailed)
      }
    }
  }
}

fn dispatch(
  account: Account,
  _capability: DebitAccount,
  destination: String,
  amount: Int,
  message_id: String,
) -> Reply {
  actor.call(process.named_subject(account.name), 5000, fn(reply_to) {
    Withdraw(
      reply_to: reply_to,
      destination: destination,
      message_id: message_id,
      amount: amount,
    )
  })
}

pub fn withdraw(
  account: Account,
  capability: DebitAccount,
  amount: Int,
  message_id: String,
) -> Reply {
  dispatch(account, capability, account.entity_id, amount, message_id)
}

pub fn balance(account: Account) -> Int {
  actor.call(process.named_subject(account.name), 5000, Balance)
}

pub fn dispatch_external(
  account: Account,
  value: dynamic.Dynamic,
) -> Result(Reply, ExternalMessageRejected) {
  let decoder = {
    use destination <- decode.field("destination", decode.string)
    use message_id <- decode.field("message_id", decode.string)
    use amount <- decode.field("amount", decode.int)
    decode.success(#(destination, message_id, amount))
  }
  case decode.run(value, decoder) {
    Ok(#(destination, message_id, amount)) ->
      Ok(dispatch(account, debit_account(), destination, amount, message_id))
    Error(_) -> Error(ExternalMessageRejected)
  }
}

pub fn force_failure(account: Account) -> Nil {
  actor.send(process.named_subject(account.name), ForceFailure)
}

pub fn account_pid(account: Account) -> Result(process.Pid, Nil) {
  process.named(account.name)
}

pub fn lookup(account: Account) -> Result(Account, Nil) {
  case process.named(account.name) {
    Ok(_) -> Ok(account)
    Error(_) -> Error(Nil)
  }
}

pub fn supervisor_alive(account: Account) -> Bool {
  process.is_alive(account.supervisor_pid)
}

pub fn stop(account: Account) -> Nil {
  actor.call(process.named_subject(account.name), 5000, Stop)
}
