// Generated by BANG M018. Do not edit.
// Checked Core: Account.withdraw, WithdrawAccountOnce, DebitAccount, WithdrawalRejectedOnce.
// This module is a deterministic target projection, not a Core authority.
import { Cause, Context, Effect, Layer, Option, Ref, Schema } from "effect";

export const AccountState = Schema.Struct({
  balance: Schema.BigInt,
});
export type AccountState = typeof AccountState.Type;

export const withdrawAccountOnceDestination = "account-1" as const;

export const isWithdrawEnabled = (state: AccountState, amount: bigint): boolean =>
  state.balance >= 0n && amount >= 0n && state.balance >= amount;

export class WithdrawalRejectedOnce extends Schema.TaggedError<WithdrawalRejectedOnce>()(
  "WithdrawalRejectedOnce",
  {
    state: AccountState,
    amount: Schema.BigInt,
  },
) {}

export class WithdrawAccountOnceWrongDestinationError extends Schema.TaggedError<WithdrawAccountOnceWrongDestinationError>()(
  "WithdrawAccountOnceWrongDestinationError",
  {
    destination: Schema.String,
    expectedDestination: Schema.Literal("account-1"),
    state: AccountState,
    amount: Schema.BigInt,
    grantId: Schema.String,
  },
) {}

export class DebitAccountGrantAlreadyConsumed extends Schema.TaggedError<DebitAccountGrantAlreadyConsumed>()(
  "DebitAccountGrantAlreadyConsumed",
  {
    grantId: Schema.String,
    remainingUses: Schema.Literal(0),
  },
) {}

export interface DebitAccountGrant {
  readonly _tag: "DebitAccountGrant";
  readonly grantId: string;
}

type DebitAccountGrantState = "available" | "consumed";
const grantStates = new WeakMap<DebitAccountGrant, Ref.Ref<DebitAccountGrantState>>();

const makeDebitAccountGrant = (grantId: string): Effect.Effect<DebitAccountGrant> =>
  Effect.gen(function* () {
    const grant = Object.freeze({ _tag: "DebitAccountGrant" as const, grantId });
    grantStates.set(grant, yield* Ref.make<DebitAccountGrantState>("available"));
    return grant;
  });

export const debitAccountGrantRemainingUses = (grant: DebitAccountGrant): Effect.Effect<number> =>
  Effect.gen(function* () {
    const state = grantStates.get(grant);
    if (state === undefined) return 0;
    return (yield* Ref.get(state)) === "available" ? 1 : 0;
  });

const consumeDebitAccountGrant = (
  grant: DebitAccountGrant,
): Effect.Effect<void, DebitAccountGrantAlreadyConsumed> =>
  Effect.gen(function* () {
    const state = grantStates.get(grant);
    if (state === undefined) {
      return yield* new DebitAccountGrantAlreadyConsumed({
        grantId: grant.grantId,
        remainingUses: 0,
      });
    }
    const consumed = yield* Ref.modify(state, (current) =>
      current === "available" ? [true, "consumed" as const] : ([false, current] as const),
    );
    if (!consumed) {
      return yield* new DebitAccountGrantAlreadyConsumed({
        grantId: grant.grantId,
        remainingUses: 0,
      });
    }
  });

export interface DebitAccountShape {
  readonly issueGrant: Effect.Effect<DebitAccountGrant>;
}

export class DebitAccount extends Context.Service<DebitAccount, DebitAccountShape>()(
  "@bang/capability/DebitAccount",
) {}

export const makeDebitAccountLayer = (grantPrefix = "grant"): Layer.Layer<DebitAccount> =>
  Layer.effect(
    DebitAccount,
    Effect.gen(function* () {
      const nextGrantId = yield* Ref.make(0);
      return DebitAccount.of({
        issueGrant: Ref.modify(nextGrantId, (current) => [current + 1, current + 1] as const).pipe(
          Effect.flatMap((ordinal) => makeDebitAccountGrant(`${grantPrefix}-${ordinal}`)),
        ),
      });
    }),
  );

export const debitAccountLayer = makeDebitAccountLayer();

export interface WithdrawAccountOnceShape {
  readonly withdraw: (
    grant: DebitAccountGrant,
    destination: string,
    state: AccountState,
    amount: bigint,
  ) => Effect.Effect<
    AccountState,
    | WithdrawalRejectedOnce
    | WithdrawAccountOnceWrongDestinationError
    | DebitAccountGrantAlreadyConsumed,
    DebitAccount
  >;
  readonly implementationCalls: Effect.Effect<number>;
}

export type WithdrawAccountOnceRequirements = DebitAccount;

export class WithdrawAccountOnce extends Context.Service<
  WithdrawAccountOnce,
  WithdrawAccountOnceShape
>()("@bang/realization/WithdrawAccountOnce") {}

export interface WithdrawAccountOnceImplementation {
  readonly withdraw: (
    state: AccountState,
    amount: bigint,
  ) => Effect.Effect<AccountState, WithdrawalRejectedOnce>;
}

export const makeWithdrawAccountOnceLayer = (
  implementation: WithdrawAccountOnceImplementation,
): Layer.Layer<WithdrawAccountOnce> =>
  Layer.effect(
    WithdrawAccountOnce,
    Effect.gen(function* () {
      const implementationCalls = yield* Ref.make(0);
      const runImplementation = Effect.fn("WithdrawAccountOnce.implementation")(function* (
        state: AccountState,
        amount: bigint,
      ): Effect.fn.Return<AccountState, WithdrawalRejectedOnce> {
        yield* Ref.update(implementationCalls, (current) => current + 1);
        return yield* implementation.withdraw(state, amount);
      });
      return WithdrawAccountOnce.of({
        withdraw: Effect.fn("WithdrawAccountOnce.withdraw")(function* (
          grant: DebitAccountGrant,
          destination: string,
          state: AccountState,
          amount: bigint,
        ): Effect.fn.Return<
          AccountState,
          | WithdrawalRejectedOnce
          | WithdrawAccountOnceWrongDestinationError
          | DebitAccountGrantAlreadyConsumed,
          DebitAccount
        > {
          if (destination !== withdrawAccountOnceDestination) {
            return yield* new WithdrawAccountOnceWrongDestinationError({
              destination,
              expectedDestination: withdrawAccountOnceDestination,
              state,
              amount,
              grantId: grant.grantId,
            });
          }
          if (!isWithdrawEnabled(state, amount)) {
            return yield* new WithdrawalRejectedOnce({
              state,
              amount,
            });
          }
          yield* DebitAccount;
          yield* consumeDebitAccountGrant(grant);
          return yield* runImplementation(state, amount);
        }),
        implementationCalls: Ref.get(implementationCalls),
      });
    }),
  );

export const WithdrawAccountOnceSuccess = Schema.TaggedStruct("Success", {
  state: AccountState,
  remainingUses: Schema.Int,
  implementationCalls: Schema.Int,
}).annotate({ parseOptions: { onExcessProperty: "error" } });
export const WithdrawAccountOnceDomainRejected = Schema.TaggedStruct("DomainRejected", {
  failure: Schema.Literal("WithdrawalRejectedOnce"),
  state: AccountState,
  amount: Schema.BigInt,
  remainingUses: Schema.Int,
  implementationCalls: Schema.Int,
}).annotate({ parseOptions: { onExcessProperty: "error" } });
export const WithdrawAccountOnceCapabilityUseRejected = Schema.TaggedStruct(
  "CapabilityUseRejected",
  {
    failure: Schema.Literal("DebitAccountGrantAlreadyConsumed"),
    state: AccountState,
    amount: Schema.BigInt,
    remainingUses: Schema.Int,
    implementationCalls: Schema.Int,
  },
).annotate({ parseOptions: { onExcessProperty: "error" } });
export const WithdrawAccountOnceWrongDestination = Schema.TaggedStruct("WrongDestination", {
  destination: Schema.String,
  expectedDestination: Schema.String,
  state: AccountState,
  amount: Schema.BigInt,
  remainingUses: Schema.Int,
  implementationCalls: Schema.Int,
}).annotate({ parseOptions: { onExcessProperty: "error" } });
export const WithdrawAccountOnceDefect = Schema.TaggedStruct("Defect", {
  failure: Schema.String,
  state: AccountState,
  amount: Schema.BigInt,
  defect: Schema.String,
  remainingUses: Schema.Int,
  implementationCalls: Schema.Int,
}).annotate({ parseOptions: { onExcessProperty: "error" } });
export const WithdrawAccountOnceObservation = Schema.Union([
  WithdrawAccountOnceSuccess,
  WithdrawAccountOnceDomainRejected,
  WithdrawAccountOnceCapabilityUseRejected,
  WithdrawAccountOnceWrongDestination,
  WithdrawAccountOnceDefect,
])
  .pipe(Schema.toTaggedUnion("_tag"))
  .annotate({
    parseOptions: { onExcessProperty: "error" },
  });
export type WithdrawAccountOnceObservation = typeof WithdrawAccountOnceObservation.Type;

export const observeWithdrawAccountOnce = Effect.fn("observeWithdrawAccountOnce")(function* (
  grant: DebitAccountGrant,
  destination: string,
  state: AccountState,
  amount: bigint,
): Effect.fn.Return<WithdrawAccountOnceObservation, never, WithdrawAccountOnce | DebitAccount> {
  const service = yield* WithdrawAccountOnce;
  const exit = yield* Effect.exit(service.withdraw(grant, destination, state, amount));
  const remainingUses = yield* debitAccountGrantRemainingUses(grant);
  const implementationCalls = yield* service.implementationCalls;
  if (exit._tag === "Success") {
    return {
      _tag: "Success",
      state: exit.value,
      remainingUses,
      implementationCalls,
    };
  }
  const cause = exit.cause;
  if (Cause.hasDies(cause)) {
    return {
      _tag: "Defect",
      failure: "implementation-defect",
      state,
      amount,
      defect: Cause.pretty(cause),
      remainingUses,
      implementationCalls,
    };
  }
  const error = Cause.findErrorOption(cause);
  if (Option.isSome(error)) {
    if (error.value instanceof WithdrawalRejectedOnce) {
      return {
        _tag: "DomainRejected",
        failure: "WithdrawalRejectedOnce",
        state: error.value.state,
        amount: error.value.amount,
        remainingUses,
        implementationCalls,
      };
    }
    if (error.value instanceof DebitAccountGrantAlreadyConsumed) {
      return {
        _tag: "CapabilityUseRejected",
        failure: "DebitAccountGrantAlreadyConsumed",
        state,
        amount: amount,
        remainingUses,
        implementationCalls,
      };
    }
    if (error.value instanceof WithdrawAccountOnceWrongDestinationError) {
      return {
        _tag: "WrongDestination",
        destination: error.value.destination,
        expectedDestination: error.value.expectedDestination,
        state: error.value.state,
        amount: error.value.amount,
        remainingUses,
        implementationCalls,
      };
    }
  }
  return {
    _tag: "Defect",
    failure: "implementation-defect",
    state,
    amount,
    defect: Cause.pretty(cause),
    remainingUses,
    implementationCalls,
  };
});
