import type { ServiceDeclaration } from "./core.ts";

const projectType = (reference: string): string => {
  switch (reference) {
    case "String":
      return "string";
    case "Integer":
      return "number";
    default:
      return "never";
  }
};

export const projectEffectService = (service: ServiceDeclaration): string => {
  const operations = service.operations
    .map((operation) => {
      const parameters = operation.parameters
        .map(({ id, type }) => `${id}: ${projectType(type)}`)
        .join(", ");
      return `  readonly ${operation.id}: (${parameters}) => Effect.Effect<${projectType(operation.result)}>;`;
    })
    .join("\n");

  return `// Generated by BANG M000. Do not edit.\nimport * as Context from "effect/Context";\nimport type * as Effect from "effect/Effect";\n\nexport interface ${service.id}Shape {\n${operations}\n}\n\nexport class ${service.id} extends Context.Service<${service.id}, ${service.id}Shape>()(\n  "@bang/${service.id}",\n) {}\n`;
};
